const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const examples=['H2 + O2 -> H2O','Fe + O2 -> Fe2O3','C3H8 + O2 -> CO2 + H2O','NaOH + HCl -> NaCl + H2O','Al + HCl -> AlCl3 + H2'];
const atomicPattern=/([A-Z][a-z]?)(\d*)/g;
function parseFormula(f){const m={};let x;f=f.trim();atomicPattern.lastIndex=0;while((x=atomicPattern.exec(f))){m[x[1]]=(m[x[1]]||0)+(+(x[2]||1))}return m}
function parseEquation(raw){let s=raw.replace(/→|⟶|=/g,'->').replace(/\s+/g,' ').trim();let parts=s.split(/->/);if(parts.length!==2)return null;let sides=parts.map(side=>side.split('+').map(v=>v.trim()).filter(Boolean));if(sides.some(x=>!x.length))return null;return sides.map(side=>side.map(item=>{let m=item.match(/^(\d+)\s*(.*)$/);return{coef:m?+m[1]:1,formula:m?m[2]:item}}))}
function elements(eq){const out=new Set();eq.flat().forEach(x=>Object.keys(parseFormula(x.formula)).forEach(e=>out.add(e)));return[...out]}
function counts(eq,side){const o={};eq[side].forEach(x=>{const f=parseFormula(x.formula);Object.entries(f).forEach(([e,n])=>o[e]=(o[e]||0)+n*x.coef)});return o}
function gcd(a,b){while(b){[a,b]=[b,a%b]}return Math.abs(a)}function gcdArr(a){return a.reduce(gcd,0)}
function matrixSolve(eq){const es=elements(eq),cols=eq[0].length+eq[1].length;let A=es.map(e=>eq[0].concat(eq[1]).map((x,i)=>(i<eq[0].length?1:-1)*parseFormula(x.formula)[e]||0)),rows=A.length,r=0,piv=[];for(let c=0;c<cols&&r<rows;c++){let k=r;for(let i=r+1;i<rows;i++)if(Math.abs(A[i][c])>Math.abs(A[k][c]))k=i;if(Math.abs(A[k][c])<1e-10)continue;[A[r],A[k]]=[A[k],A[r]];let q=A[r][c];A[r]=A[r].map(v=>v/q);for(let i=0;i<rows;i++)if(i!==r&&Math.abs(A[i][c])>1e-10){let q2=A[i][c];A[i]=A[i].map((v,j)=>v-q2*A[r][j])}piv.push(c);r++}let free=[];for(let c=0;c<cols;c++)if(!piv.includes(c))free.push(c);if(!free.length)return null;let v=Array(cols).fill(0);v[free[0]]=1;for(let i=piv.length-1;i>=0;i--){let c=piv[i],sum=0;for(let j=c+1;j<cols;j++)sum+=A[i][j]*v[j];v[c]=-sum/A[i][c]}let scale=1000000;v=v.map(x=>Math.round(x*scale));let g=gcdArr(v);v=v.map(x=>x/g);if(v.some(x=>x<0))v=v.map(x=>-x);g=gcdArr(v);return v.map(x=>x/g)}
function pretty(eq,coefs){let i=0;return eq.map(side=>side.map(x=>{let c=coefs[i++];return(c===1?'':c)+formatFormula(x.formula)}).join(' + ')).join(' → ')}
function formatFormula(f){return f.replace(/([A-Z][a-z]?)(\d+)/g,'$1<sub>$2</sub>')}
function balance(raw){const eq=parseEquation(raw);if(!eq)return null;const cs=matrixSolve(eq);if(!cs)return null;return{eq,cs,text:pretty(eq,cs)}}
function showBalance(raw){const r=balance(raw),box=$('#balanceResult');box.classList.remove('hidden');if(!r){box.innerHTML='<b>Could not balance this equation.</b><p>Check the formulas and use an arrow (→ or -&gt;). Complex ionic equations may need to be entered in a simpler form.</p>';return}let steps=r.eq[0].concat(r.eq[1]).map((x,i)=>`${r.cs[i]} × ${x.formula}`).join(' &nbsp; ');box.innerHTML=`<div class="equation">${r.text}</div><div class="steps-result"><div class="step"><i>1</i><div><b>Find the atom counts.</b><br>Each element must be conserved from reactants to products.</div></div><div class="step"><i>2</i><div><b>Determine coefficient ratios.</b><br>The smallest whole-number coefficients are <b>${r.cs.join(' : ')}</b>.</div></div><div class="step"><i>3</i><div><b>Verify.</b><br>Coefficients applied: ${steps}. Recounting every element gives equal totals on both sides.</div></div></div>`}
$('#balanceBtn').onclick=()=>showBalance($('#equationInput').value);$('#equationInput').addEventListener('keydown',e=>{if(e.key==='Enter')showBalance(e.target.value)});$$('[data-eq]').forEach(b=>b.onclick=()=>{$('#equationInput').value=b.dataset.eq;showBalance(b.dataset.eq)});$('#exampleBtn').onclick=()=>{let x=examples[Math.floor(Math.random()*examples.length)];$('#equationInput').value=x;showBalance(x)};
$('#checkBtn').onclick=()=>{const raw=$('#checkInput').value,eq=parseEquation(raw),box=$('#checkResult');if(!eq){box.innerHTML='<p style="color:var(--bad)"><b>Could not read the equation.</b> Use a format such as 2H2 + O2 → 2H2O.</p>';return}let L=counts(eq,0),R=counts(eq,1),es=[...new Set([...Object.keys(L),...Object.keys(R)])],bad=es.filter(e=>(L[e]||0)!==(R[e]||0));if(bad.length){let detail=bad.map(e=>`${e}: ${L[e]||0} left vs ${R[e]||0} right`).join(' · ');box.innerHTML=`<div class="result" style="color:var(--bad)"><b>✕ Not balanced</b><p>${detail}</p><small>Try changing coefficients, not subscripts. The correct balance is: ${balance(raw)?balance(raw).text:'unable to calculate'}</small></div>`}else{let cs=eq[0].concat(eq[1]).map(x=>x.coef),g=gcdArr(cs);let simple=g===1;box.innerHTML=`<div class="result" style="color:var(--good)"><b>✓ Balanced!</b><p>Every element has the same number of atoms on both sides.${simple?' The coefficients are already in simplest whole-number ratio.':' You can divide all coefficients by their common factor.'}</p></div>`}};
const quizPool=[['H2 + O2 → H2O','2H2 + O2 → 2H2O'],['Fe + O2 → Fe2O3','4Fe + 3O2 → 2Fe2O3'],['C3H8 + O2 → CO2 + H2O','C3H8 + 5O2 → 3CO2 + 4H2O'],['NaOH + HCl → NaCl + H2O','NaOH + HCl → NaCl + H2O'],['Al + HCl → AlCl3 + H2','2Al + 6HCl → 2AlCl3 + 3H2'],['KClO3 → KCl + O2','2KClO3 → 2KCl + 3O2'],['Mg + O2 → MgO','2Mg + O2 → 2MgO'],['N2 + H2 → NH3','N2 + 3H2 → 2NH3'],['CaCO3 → CaO + CO2','CaCO3 → CaO + CO2'],['CH4 + O2 → CO2 + H2O','CH4 + 2O2 → CO2 + 2H2O'],['Zn + HCl → ZnCl2 + H2','Zn + 2HCl → ZnCl2 + H2'],['AgNO3 + NaCl → AgCl + NaNO3','AgNO3 + NaCl → AgCl + NaNO3'],['Na + Cl2 → NaCl','2Na + Cl2 → 2NaCl'],['H2SO4 + NaOH → Na2SO4 + H2O','H2SO4 + 2NaOH → Na2SO4 + 2H2O'],['P + O2 → P2O5','4P + 5O2 → 2P2O5']];let currentQuiz=[];
function makeQuiz(){let n=+$('#questionCount').value;currentQuiz=[...quizPool].sort(()=>Math.random()-.5).slice(0,n);$('#quizArea').innerHTML=currentQuiz.map((q,i)=>`<div class="quiz-q" id="q${i}"><div class="qtext">${i+1}. Balance: ${q[0]}</div><input data-i="${i}" placeholder="Your balanced equation"><div class="feedback"></div></div>`).join('')+`<button class="primary" id="submitQuiz">Submit answers</button>`;$('#scoreArea').innerHTML='';$('#submitQuiz').onclick=gradeQuiz}
function gradeQuiz(){let score=0;currentQuiz.forEach((q,i)=>{let el=$(`#q${i}`),ans=el.querySelector('input').value.trim(),fb=el.querySelector('.feedback'),a=balance(ans),target=balance(q[0]),ok=a&&target&&a.text.replace(/\s/g,'')===target.text.replace(/\s/g,'');el.classList.toggle('correct',ok);el.classList.toggle('incorrect',!ok);if(ok){score++;fb.innerHTML='<span style="color:var(--good)">✓ Correct</span>'}else fb.innerHTML=`<span style="color:var(--bad)">✕ Correct answer: ${q[1]}</span>`});$('#scoreArea').innerHTML=`<div class="score">Score: ${score} / ${currentQuiz.length} (${Math.round(score/currentQuiz.length*100)}%)</div>`}
$('#newQuiz').onclick=makeQuiz;makeQuiz();
$('#shareQuiz').onclick=async()=>{let text='Chemistry Equations practice test\n\n'+currentQuiz.map((q,i)=>`${i+1}. Balance: ${q[0]}`).join('\n');try{await navigator.clipboard.writeText(text);toast('Test copied to clipboard — share it anywhere.')}catch(e){toast('Copy failed; you can use Print / PDF instead.')}};
$('#printQuiz').onclick=()=>{const answers=currentQuiz.map((q,i)=>`${i+1}. ${q[1]}`).join('\n');const blank=currentQuiz.map((q,i)=>`${i+1}. Balance: ${q[0]}\n\nAnswer: ______________________________`).join('\n\n');const w=window.open('','_blank');w.document.write(`<html><head><title>Chemistry Equations Test</title><style>body{font:16px Arial;max-width:750px;margin:40px auto;line-height:1.6}.page{page-break-after:always}h1{margin-bottom:30px}</style></head><body><div class="page"><h1>Chemistry Equations — Blank Test</h1><p>Name: ____________________ &nbsp; Date: __________</p><pre style="font:16px Arial;white-space:pre-wrap">${blank}</pre></div><h1>Answer Key</h1><pre style="font:16px Arial;white-space:pre-wrap">${answers}</pre><script>window.print()<\/script></body></html>`);w.document.close()};
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}
$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');
const canvas=$('#pad'),ctx=canvas.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';let drawing=false,last=null;function pos(e){let r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}}function start(e){drawing=true;last=pos(e);e.preventDefault()}function move(e){if(!drawing)return;let p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;e.preventDefault()}function end(){drawing=false}canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);window.addEventListener('mouseup',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end);$('#clearPad').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);$$('[data-symbol]').forEach(b=>b.onclick=()=>{let v=$('#equationInput');v.value+=(v.value?' ':'')+b.dataset.symbol});

// Handwriting recognition: Cloudflare Workers AI first, then local Tesseract OCR.
const normalizeOCR=s=>{let t=(s||'').replace(/[\r\n]+/g,' ').replace(/[→⟶➜⇒]/g,' -> ').replace(/[×x]/g,' + ').replace(/[–—−]/g,'-').replace(/[^A-Za-z0-9+>\-\s]/g,' ').replace(/\s+/g,' ').trim();t=t.replace(/\s*[-]+>\s*/g,' -> ');return t};
async function recognizeWithCloudflare(dataUrl){const base=window.CHEMISTRY_HANDWRITING_WORKER;if(!base)throw new Error('Worker URL unavailable');const res=await fetch(base.replace(/\/$/,'')+'/recognize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:dataUrl})});if(!res.ok)throw new Error('Cloudflare recognition failed');const data=await res.json();if(!data.text)throw new Error('No equation recognized');return normalizeOCR(data.text)}
async function recognizeInBrowser(dataUrl){if(!window.Tesseract)throw new Error('Browser OCR unavailable');const out=await Tesseract.recognize(dataUrl,'eng',{logger:m=>{if(m.status&&typeof m.progress==='number')$('#recognitionStatus').textContent=`Browser OCR: ${m.status} ${Math.round(m.progress*100)}%`}});return normalizeOCR(out.data.text)}
async function recognizeHandwriting(){const status=$('#recognitionStatus'),out=$('#recognitionResult');out.classList.remove('hidden');status.textContent='Trying Cloudflare AI…';out.innerHTML='<p>Recognizing handwriting…</p>';const dataUrl=canvas.toDataURL('image/png');let text='';try{text=await recognizeWithCloudflare(dataUrl);status.textContent='Recognized with Cloudflare AI';}catch(e){try{status.textContent='Cloudflare unavailable — using browser OCR…';text=await recognizeInBrowser(dataUrl);status.textContent='Recognized locally in your browser';}catch(e2){status.textContent='Recognition failed';out.innerHTML='<p style="color:var(--bad)"><b>Could not recognize the handwriting.</b> Try writing larger/clearer, or use the keyboard field.</p>';return}}if(!text||!text.includes('->')){out.innerHTML=`<p><b>Recognized:</b> ${text||'nothing'}</p><p>Tip: make the arrow and plus signs clear, then try again.</p>`;return}$('#equationInput').value=text;out.innerHTML=`<p><b>Recognized:</b> ${text}</p><button id="useRecognized" class="primary">Balance recognized equation</button>`;$('#useRecognized').onclick=()=>showBalance(text)}
$('#usePad').onclick=recognizeHandwriting;
