(()=>{
'use strict';
const input=document.getElementById('equationInput'),btn=document.getElementById('balanceBtn'),out=document.getElementById('balanceResult');
if(!input||!btn||!out)return;
const symbols=window.CHEMISTRY_ELEMENT_SYMBOLS;if(!symbols)return;
const digits='₀₁₂₃₄₅₆₇₈₉';
const subDigits={'0':'₀','1':'₁','2':'₂','3':'₃','4':'₄','5':'₅','6':'₆','7':'₇','8':'₈','9':'₉'};
const normalize=s=>String(s||'').replace(/[₀₁₂₃₄₅₆₇₈₉]/g,c=>'0123456789'[digits.indexOf(c)]).replace(/⟶|⇒|➜|⟹|⟾|=>|->/g,'→').replace(/=(?!>)/g,'→').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prettyFormula=src=>{const raw=String(src??'').replace(/\s*\((aq|s|l|g)\)\s*$/i,(_,state)=>`(${state.toLowerCase()})`).replace(/[₀₁₂₃₄₅₆₇₈₉]/g,c=>({'₀':'0','₁':'1','₂':'2','₃':'3','₄':'4','₅':'5','₆':'6','₇':'7','₈':'8','₉':'9'}[c]));const safe=esc(raw);let out='',i=0;while(i<safe.length){if(/\d/.test(safe[i])){let j=i;while(j<safe.length&&/\d/.test(safe[j]))j++;out+=safe.slice(i,j).replace(/\d/g,d=>subDigits[d]);i=j;continue}out+=safe[i++]}return out};
const prettyEquation=eq=>String(eq||'').replace(/[⟶⇒➜⟹⟾]/g,'→').replace(/\s*(?:=>|->|→)\s*/g,' → ').split(' → ').map(side=>side.split(/\s*\+\s*/).map(part=>{const m=part.trim().match(/^(\d+)\s*(.*)$/);return m?`${m[1]==='1'?'':m[1]}${prettyFormula(m[2])}`:prettyFormula(part.trim())}).join(' + ')).join(' → ');
const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a};
const lcm=(a,b)=>Math.abs(a/gcd(a,b)*b);
function parseFormula(text){const s=String(text||'').replace(/\s+/g,'');let i=0;const fail=(message,pos=i,problem='')=>{const e=new Error(message);e.formulaIndex=pos;e.problem=problem||s.slice(pos);throw e};function group(close){const a={};while(i<s.length){if(close&&s[i]===close){i++;return a}if(s[i]===')')fail('Unexpected closing parenthesis.',i,')');if(s[i]==='('){i++;const g=group(')'),n=s.slice(i).match(/^\d+/),mult=n?+n[0]:1;if(n)i+=n[0].length;if(mult<=0)fail('Subscripts must be positive integers.',Math.max(0,i-(n?.[0]?.length||1)),n?.[0]||'');for(const e in g)a[e]=(a[e]||0)+g[e]*mult;continue}const em=s.slice(i).match(/^[A-Z][a-z]?/);if(!em){const token=s.slice(i)||' ';if(/^[a-z]/.test(token))fail(`Invalid element symbol “${s[i]}”.`,i,s[i]);if(/^\d/.test(token))fail(`Invalid formula near “${token}”.`,i,token);fail(`Invalid formula near “${token}”.`,i,token)}const e=em[0];if(!symbols.has(e))fail(`Invalid element symbol “${e}”.`,i,e);i+=e.length;const n=s.slice(i).match(/^\d+/),mult=n?+n[0]:1;if(n)i+=n[0].length;if(mult<=0)fail('Subscripts must be positive integers.',Math.max(0,i-(n?.[0]?.length||1)),n?.[0]||'');a[e]=(a[e]||0)+mult}if(close)fail('Missing closing parenthesis.',s.length-1,close);return a}return group()}
function parseStage(raw){const s=normalize(raw),ar=[...s.matchAll(/→/g)];if(ar.length===0)throw Object.assign(new Error('Please enter both sides of the equation.'),{kind:'side'});if(ar.length!==1)throw Object.assign(new Error('Please use exactly one reaction arrow (→, ->, or =>).'),{kind:'arrow',arrowCount:ar.length});const a=ar[0],L=s.slice(0,a.index).trim(),R=s.slice(a.index+1).trim();if(!L||!R)throw Object.assign(new Error('Please enter both sides of the equation.'),{kind:'side'});const side=t=>t.split('+').map(x=>{const z=x.trim();if(!z)throw new Error('Please enter a formula on both sides of the equation.');const m=z.match(/^(\d+)\s*(.+)$/),f=(m?m[2]:z).trim(),coef=m?+m[1]:1;const formula=f.replace(/\s*\((?:aq|s|l|g)\)\s*$/i,'').trim();if(coef<=0)throw new Error('Coefficients must be positive whole numbers.');try{return{f,a:parseFormula(formula),originalCoef:coef}}catch(e){e.problem=e.problem||formula;throw e}});return{left:side(L),right:side(R)}}
function solve(eq){const all=[...eq.left,...eq.right],els=[...new Set(all.flatMap(x=>Object.keys(x.a)))],n=all.length,m=els.length;if(n<2)return null;const A=els.map(e=>all.map((x,i)=>(i<eq.left.length?1:-1)*(x.a[e]||0))),rows=A.map(r=>r.map(Number));let r=0,piv=[];for(let c=0;c<n&&r<m;c++){let q=r;for(let k=r+1;k<m;k++)if(Math.abs(rows[k][c])>Math.abs(rows[q][c]))q=k;if(Math.abs(rows[q][c])<1e-12)continue;[rows[r],rows[q]]=[rows[q],rows[r]];const d=rows[r][c];for(let j=c;j<n;j++)rows[r][j]/=d;for(let k=0;k<m;k++)if(k!==r){const f=rows[k][c];if(Math.abs(f)>1e-12)for(let j=c;j<n;j++)rows[k][j]-=f*rows[r][j]}piv.push(c);r++}for(let k=r;k<m;k++)if(rows[k].some(x=>Math.abs(x)>1e-10))return null;const free=[];for(let c=0;c<n;c++)if(!piv.includes(c))free.push(c);if(!free.length)return null;let answer=null;const vals=Array(free.length).fill(1);function attempt(pos){if(answer)return;if(pos===free.length){const v=Array(n).fill(0);free.forEach((c,i)=>v[c]=vals[i]);for(let q=piv.length-1;q>=0;q--){const c=piv[q];let z=0;for(let j=c+1;j<n;j++)z+=rows[q][j]*v[j];v[c]=-z}if(v.some(x=>!Number.isFinite(x)||x<=1e-10))return;let den=1;for(const x of v){let found=false;for(let d=1;d<=1200;d++)if(Math.abs(x*d-Math.round(x*d))<1e-8){den=lcm(den,d);found=true;break}if(!found)return}let co=v.map(x=>Math.round(x*den)),g=co.reduce(gcd,0);if(g)co=co.map(x=>x/g);if(co.some(x=>x<=0||x>100000))return;for(let i=0;i<m;i++){let sum=0;for(let j=0;j<n;j++)sum+=A[i][j]*co[j];if(sum!==0)return}answer=co;return}for(let x=1;x<=12&&!answer;x++){vals[pos]=x;attempt(pos+1)}}attempt(0);return answer}
function atomCounts(eq,co){const L={},R={};let i=0;for(const x of eq.left){const c=co[i++];for(const[e,n]of Object.entries(x.a))L[e]=(L[e]||0)+n*c}for(const x of eq.right){const c=co[i++];for(const[e,n]of Object.entries(x.a))R[e]=(R[e]||0)+n*c}return{L,R}}
function balancedByInput(eq){const all=[...eq.left,...eq.right],co=all.map(x=>x.originalCoef),{L,R}=atomCounts(eq,co),els=[...new Set([...Object.keys(L),...Object.keys(R)])];return els.every(e=>(L[e]||0)===(R[e]||0))}
function changedMarkup(item,newCoef){const changed=item.originalCoef!==newCoef,coef=newCoef===1?'':String(newCoef);return `<span class="coefficient ${changed?'coefficient-changed':''}" title="${changed?'Coefficient changed from '+item.originalCoef+' to '+newCoef:''}">${coef}</span>${prettyFormula(item.f)}`}
function renderBalanced(eq,co){let i=0;const side=a=>a.map(item=>changedMarkup(item,co[i++])).join(' + ');return `${side(eq.left)} <span class="reaction-arrow">→</span> ${side(eq.right)}`}
function setStatus(kind,text){return `<div class="balance-status balance-status-${kind}"><b>${kind==='good'?'✓':kind==='bad'?'✗':'⚠'} ${text}</b></div>`}
function showError(e){out.classList.remove('hidden');input.setAttribute('aria-invalid','true');const problem=e.problem?`<p><b>Problem found:</b> <mark>${prettyFormula(e.problem)}</mark></p>`:'';out.innerHTML=`${setStatus('bad','Invalid equation')}<div class="validation-error"><p>${esc(e.message)}</p>${problem}<p class="muted">Please check the formulas and reaction arrow.</p></div>`}
function balance(){out.classList.add('hidden');input.removeAttribute('aria-invalid');try{const raw=String(input.value||'').trim();if(!raw)throw new Error('Please enter an equation first.');const eq=parseStage(raw),originalBalanced=balancedByInput(eq),co=solve(eq);if(!co)throw new Error('This equation could not be solved.');if(originalBalanced){out.innerHTML=`${setStatus('good','Balanced')}<div class="equation">${renderBalanced(eq,co)}</div><div class="steps-result"><b>✓ This equation is already balanced.</b><br><span class="muted">Every element count is conserved.</span></div>`}else{out.innerHTML=`${setStatus('bad','Not balanced')}<div class="balance-correction"><div class="balance-status balance-status-good"><b>✓ Balanced result</b></div><div class="equation">${renderBalanced(eq,co)}</div><div class="steps-result"><span class="muted">The highlighted coefficients were changed.</span></div></div>`}out.classList.remove('hidden')}catch(e){showError(e)}}
btn.addEventListener('click',balance);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();balance()}});document.querySelectorAll('[data-eq]').forEach(b=>b.addEventListener('click',()=>{input.value=normalize(b.dataset.eq);balance()}));document.getElementById('exampleBtn')?.addEventListener('click',()=>{const a=['H2 + O2 → H2O','Fe + O2 → Fe2O3','C3H8 + O2 → CO2 + H2O','Ca(OH)2 + HCl → CaCl2 + H2O'];input.value=a[Math.floor(Math.random()*a.length)];balance()});document.getElementById('resetBtn')?.addEventListener('click',()=>{input.value='H2 + O2 → H2O';out.classList.add('hidden');input.removeAttribute('aria-invalid');input.focus()});document.getElementById('clearBtn')?.addEventListener('click',()=>{input.value='';out.classList.add('hidden');input.removeAttribute('aria-invalid');input.focus()});
})();
