(()=>{
const API=window.CHEMISTRY_HANDWRITING_WORKER;const area=document.querySelector('#challengeArea');const host=document.querySelector('#hostSetup');if(!area||!API)return;
let timer=null,playerId=null,code=null,startMs=null,total=1;
const fmt=ms=>{const s=Math.max(0,ms)/1000;return s.toFixed(2)+' s'};
const api=async(path,opts={})=>{const r=await fetch(API.replace(/\/$/,'')+path,opts);const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(html){area.classList.remove('hidden');area.innerHTML=html}
function setupRender(questions){host.classList.remove('hidden');host.innerHTML=`<div class="section-head"><div><span class="eyebrow">HOST A CHALLENGE</span><h2>Choose the questions</h2><p>Both players will receive exactly the same questions.</p></div></div><div class="quiz-settings"><label>Question source<select id="challengeSource"><option value="random">Random questions</option><option value="suggested">Select from suggestions</option><option value="custom">Insert my own equations</option></select></label><label>Number<select id="challengeCount"><option>1</option><option>3</option><option selected>5</option><option>10</option></select></label></div><div id="suggestions" class="quiz-list hidden"></div><div id="customQuestions" class="hidden"><p class="muted">Enter one equation and its balanced answer per row.</p><div id="customRows"></div><button id="addRow" class="secondary">+ Add equation</button></div><button id="startHost" class="primary full">Create challenge</button><p id="hostError" class="error"></p>`;
const source=document.querySelector('#challengeSource'),count=document.querySelector('#challengeCount'),suggestions=document.querySelector('#suggestions'),custom=document.querySelector('#customQuestions');
const renderSuggested=()=>{suggestions.innerHTML=questions.map((q,i)=>`<label class="card" style="display:block"><input type="checkbox" class="suggestedQ" value="${i}"> <b>${escapeHtml(q.equation)}</b><div class="muted">Answer: ${escapeHtml(q.answer)}</div></label>`).join('');suggestions.classList.remove('hidden')};
const addRow=()=>{document.querySelector('#customRows').insertAdjacentHTML('beforeend',`<div class="grid-2 custom-row"><input class="customEq" placeholder="Equation, e.g. H2 + O2 → H2O"><input class="customAns" placeholder="Balanced answer, e.g. 2H2 + O2 → 2H2O"></div>`)};
source.onchange=()=>{suggestions.classList.add('hidden');custom.classList.add('hidden');if(source.value==='suggested')renderSuggested();if(source.value==='custom'){custom.classList.remove('hidden');if(!document.querySelector('.custom-row')){addRow();addRow()}}};document.querySelector('#addRow').onclick=addRow;
document.querySelector('#startHost').onclick=async()=>{try{let qs=[];if(source.value==='random'){const n=Number(count.value);qs=[...questions].sort(()=>Math.random()-.5).slice(0,n)}else if(source.value==='suggested'){qs=[...document.querySelectorAll('.suggestedQ:checked')].map(x=>questions[Number(x.value)]);if(!qs.length)throw new Error('Select at least one suggested question.')}else{document.querySelectorAll('.custom-row').forEach(r=>{const equation=r.querySelector('.customEq').value.trim(),answer=r.querySelector('.customAns').value.trim();if(equation&&answer)qs.push({equation,answer})});if(!qs.length)throw new Error('Enter at least one equation and balanced answer.')}const name=prompt('Your name for the challenge:','Host')||'Host';const d=await api('/challenge/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questions:qs})});code=d.code;const j=await api('/challenge/'+code+'/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});playerId=j.playerId;total=j.questionCount;host.classList.add('hidden');render(`<div class="challenge-top"><span class="eyebrow">CHALLENGE CREATED</span><h2>Room <span>${code}</span></h2><p>Send this code to your opponent. ${total} question${total>1?'s':''} will be solved in order.</p><div class="room-code">${code}</div><p id="challengeStatus">Waiting for the second player…</p>`);poll()}catch(e){document.querySelector('#hostError').textContent=e.message}};
}
async function loadQuestions(){try{return (await api('/challenge/questions')).questions}catch(e){return []}}
async function host(){const qs=await loadQuestions();if(!qs.length){render('<p class="error">Could not load challenge questions.</p>');return}setupRender(qs)}
async function join(){const c=(prompt('Enter the challenge code:','')||'').trim().toUpperCase();if(!c)return;const name=prompt('Your name:','Player 2')||'Player 2';try{const j=await api('/challenge/'+c+'/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});code=c;playerId=j.playerId;total=j.questionCount;render(`<div class="challenge-top"><span class="eyebrow">JOINED CHALLENGE</span><h2>Get ready!</h2><p id="challengeStatus">Waiting for the other player…</p></div>`);poll()}catch(e){render(`<p class="error">${e.message}</p>`)}}
async function poll(){clearTimeout(timer);try{const d=await api('/challenge/'+code+'/status');if(d.startedAt&&!startMs){startMs=d.startedAt;showQuestion(null,d.players.find(p=>p.id===playerId)?.index||0);return}if(d.finished){showWinner(d);return}const me=d.players.find(p=>p.id===playerId);if(d.startedAt&&me&&me.index>0){showQuestion(null,me.index);return}const st=document.querySelector('#challengeStatus');if(st)st.textContent=d.players.length<2?'Waiting for the second player…':'Starting…';timer=setTimeout(poll,700)}catch(e){const st=document.querySelector('#challengeStatus');if(st)st.textContent=e.message;timer=setTimeout(poll,1500)}}
function showQuestion(q,index){area.innerHTML=`<div class="eyebrow">⚡ QUESTION ${index+1} / ${total}</div><h2>Balance this equation</h2><div class="challenge-timer" id="challengeTimer">0.00 s</div><div class="challenge-question" id="currentQuestion">${q||'Loading…'}</div><div class="challenge-answer"><input id="challengeAnswer" placeholder="Your balanced equation" autocomplete="off"><button id="challengeSubmit" class="primary">Submit answer</button></div><p id="challengeFeedback" class="muted">Your total time is measured from the start until all questions are solved.</p>`;if(q){startTimer();}else{loadCurrentQuestion(index)}}
async function loadCurrentQuestion(index){try{const d=await api('/challenge/'+code+'/status');const me=d.players.find(p=>p.id===playerId);const n=me?me.index:index;/* status intentionally omits answer; get next question by rejoining is not allowed, so refresh page data is sent by submit response */if(n===0){/* first question */const qs=await api('/challenge/questions');document.querySelector('#currentQuestion').textContent=qs.questions[0].equation}else{document.querySelector('#currentQuestion').textContent='Continue with the next question…'}startTimer()}catch(e){document.querySelector('#challengeFeedback').textContent=e.message}}
function startTimer(){const tick=()=>{const el=document.querySelector('#challengeTimer');if(!el)return;el.textContent=fmt(Date.now()-startMs);timer=setTimeout(tick,50)};tick();document.querySelector('#challengeSubmit').onclick=submit;document.querySelector('#challengeAnswer').onkeydown=e=>{if(e.key==='Enter')submit()}}
async function submit(){const inp=document.querySelector('#challengeAnswer'),fb=document.querySelector('#challengeFeedback');if(!inp||!inp.value.trim())return;document.querySelector('#challengeSubmit').disabled=true;try{const d=await api('/challenge/'+code+'/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId,answer:inp.value})});if(!d.correct){fb.innerHTML='<span class="bad">✕ Not correct — try again.</span>';document.querySelector('#challengeSubmit').disabled=false;return}if(d.finished){clearTimeout(timer);fb.innerHTML=d.winner?`<span class="good">🏆 You won in ${fmt(d.time)}!</span>`:`<span class="good">✓ Finished in ${fmt(d.time)}.</span>`;setTimeout(poll,300);return}showQuestion(d.nextQuestion,d.progress);}
catch(e){fb.textContent=e.message;document.querySelector('#challengeSubmit').disabled=false}}
function showWinner(d){clearTimeout(timer);const w=d.winner;area.innerHTML=`<div class="challenge-result"><span class="eyebrow">CHALLENGE FINISHED</span><h2>🏆 ${escapeHtml(w.name)} wins!</h2><div class="winner-time">${fmt(w.time)}</div><p>The winner is the first player to correctly finish all ${total} questions.</p><button class="secondary" onclick="location.reload()">New challenge</button></div>`}
async function leaderboard(){const box=document.querySelector('#leaderboard');if(!box)return;try{const d=await api('/challenge/leaderboard');if(!d.entries.length){box.innerHTML='<p class="muted">No challenge results yet. Be the first!</p>';return}box.innerHTML='<div class="leader-row head"><span>#</span><span>Player</span><span>Time</span></div>'+d.entries.slice(0,25).map((x,i)=>`<div class="leader-row"><span>${i+1}</span><b>${escapeHtml(x.name)}</b><span>${fmt(x.time)}</span></div>`).join('')}catch(e){box.innerHTML='<p class="error">Could not load leaderboard.</p>'}}
document.querySelector('#hostChallenge')?.addEventListener('click',host);document.querySelector('#joinChallenge')?.addEventListener('click',join);document.querySelector('#refreshLeaderboard')?.addEventListener('click',leaderboard);leaderboard();
})();