(()=>{
const API=window.CHEMISTRY_HANDWRITING_WORKER;
const area=document.querySelector('#challengeArea');
if(!area||!API)return;
let timer=null,playerId=null,code=null,startMs=null;
const fmt=ms=>{const s=Math.max(0,ms)/1000;return s.toFixed(2)+' s'};
const api=async(path,opts={})=>{const r=await fetch(API.replace(/\/$/,'')+path,opts);const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d};
function render(html){area.classList.remove('hidden');area.innerHTML=html}
async function create(){try{const name=prompt('Your name for the challenge:','Player 1')||'Player 1';const d=await api('/challenge/create',{method:'POST'});code=d.code;const j=await api('/challenge/'+code+'/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});playerId=j.playerId;render(`<div class="challenge-top"><span class="eyebrow">CHALLENGE CREATED</span><h2>Room <span>${code}</span></h2><p>Send this code to your opponent. They must join the same room.</p><div class="room-code">${code}</div><p id="challengeStatus">Waiting for the second player…</p></div>`);poll()}catch(e){render(`<p class="error">${e.message}</p>`)}}
async function join(){const c=(prompt('Enter the 5-character challenge code:','')||'').trim().toUpperCase();if(!c)return;const name=prompt('Your name:','Player 2')||'Player 2';try{const j=await api('/challenge/'+c+'/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});code=c;playerId=j.playerId;render(`<div class="challenge-top"><span class="eyebrow">JOINED CHALLENGE</span><h2>Get ready!</h2><p id="challengeStatus">Waiting for the other player…</p></div>`);poll()}catch(e){render(`<p class="error">${e.message}</p>`)}}
async function poll(){clearTimeout(timer);try{const d=await api('/challenge/'+code+'/status');if(d.startedAt&&!startMs){startMs=d.startedAt;showQuestion(d.question);return}if(d.finished){showWinner(d);return}const st=document.querySelector('#challengeStatus');if(st)st.textContent=d.players.length<2?'Waiting for the second player…':'Starting…';timer=setTimeout(poll,700)}catch(e){const st=document.querySelector('#challengeStatus');if(st)st.textContent=e.message;timer=setTimeout(poll,1500)}}
function showQuestion(q){area.innerHTML=`<div class="eyebrow">⚡ GO!</div><h2>Balance this equation first</h2><div class="challenge-timer" id="challengeTimer">0.00 s</div><div class="challenge-question">${q}</div><div class="challenge-answer"><input id="challengeAnswer" placeholder="Your balanced equation" autocomplete="off"><button id="challengeSubmit" class="primary">Submit answer</button></div><p id="challengeFeedback" class="muted">The clock started when both players were ready.</p>`;const tick=()=>{document.querySelector('#challengeTimer').textContent=fmt(Date.now()-startMs);timer=setTimeout(tick,50)};tick();document.querySelector('#challengeSubmit').onclick=submit;document.querySelector('#challengeAnswer').onkeydown=e=>{if(e.key==='Enter')submit()}}
async function submit(){const inp=document.querySelector('#challengeAnswer'),fb=document.querySelector('#challengeFeedback');if(!inp||!inp.value.trim())return;document.querySelector('#challengeSubmit').disabled=true;try{const d=await api('/challenge/'+code+'/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId,answer:inp.value})});if(!d.correct){fb.innerHTML='<span class="bad">✕ Not correct — try again.</span>';document.querySelector('#challengeSubmit').disabled=false;return}clearTimeout(timer);fb.innerHTML=d.winner?`<span class="good">🏆 You won in ${fmt(d.time)}!</span>`:`<span class="good">✓ Correct in ${fmt(d.time)}. Checking the opponent…</span>`;setTimeout(poll,300)}}catch(e){fb.textContent=e.message;document.querySelector('#challengeSubmit').disabled=false}}
function showWinner(d){clearTimeout(timer);const w=d.winner;area.innerHTML=`<div class="challenge-result"><span class="eyebrow">CHALLENGE FINISHED</span><h2>🏆 ${w.name} wins!</h2><div class="winner-time">${fmt(w.time)}</div><p>Winner is determined by the server-recorded time, so both players receive the same question and race fairly.</p><button class="secondary" onclick="location.reload()">New challenge</button></div>`}
async function leaderboard(){const box=document.querySelector('#leaderboard');try{const d=await api('/challenge/leaderboard');if(!d.entries.length){box.innerHTML='<p class="muted">No challenge results yet. Be the first!</p>';return}box.innerHTML='<div class="leader-row head"><span>#</span><span>Player</span><span>Time</span></div>'+d.entries.slice(0,25).map((x,i)=>`<div class="leader-row"><span>${i+1}</span><b>${escapeHtml(x.name)}</b><span>${fmt(x.time)}</span></div>`).join('')}catch(e){box.innerHTML='<p class="error">Could not load leaderboard.</p>'}}
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelector('#createChallenge')?.addEventListener('click',create);document.querySelector('#joinChallenge')?.addEventListener('click',join);document.querySelector('#refreshLeaderboard')?.addEventListener('click',leaderboard);leaderboard();
})();