(()=>{
'use strict';
const input=document.getElementById('checkInput'),btn=document.getElementById('checkBtn'),out=document.getElementById('checkResult');
if(!input||!btn||!out)return;
const symbols=new Set('H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr'.split(' '));
const clean=s=>String(s||'').replace(/[₀₁₂₃₄₅₆₇₈₉]/g,c=>'0123456789'['₀₁₂₃₄₅₆₇₈₉'.indexOf(c)]).replace(/⟶|⇒|➜|⟹|⟾/g,'→').replace(/=>/g,'→').replace(/=(?!>)/g,'→').replace(/\s+/g,' ').trim();
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=s=>esc(String(s||'')).replace(/([A-Z][a-z]?)(\d+)/g,'$1<sub>$2</sub>');
const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a};
function formula(s){s=String(s||'').replace(/\s+/g,'');let i=0;function fail(msg,token){const e=new Error(msg);e.problem=token||s.slice(i);throw e}function group(close){const a={};while(i<s.length){if(close&&s[i]===close){i++;return a}if(s[i]===')')fail('Unexpected closing parenthesis.',')');if(s[i]==='('){i++;const g=group(')'),m=s.slice(i).match(/^\d+/),k=m?+m[0]:1;if(m)i+=m[0].length;for(const e in g)a[e]=(a[e]||0)+g[e]*k;continue}const m=s.slice(i).match(/^[A-Z][a-z]?/);if(!m){const t=s.slice(i);if(/^[a-z]/.test(t))fail(`Invalid element symbol “${s[i]}”.`,s[i]);fail(`Invalid chemical formula near “${t}”.`,t)}const e=m[0];if(!symbols.has(e))fail(`Invalid element symbol “${e}”.`,e);i+=e.length;const n=s.slice(i).match(/^\d+/),k=n?+n[0]:1;if(n)i+=n[0].length;if(k<=0)fail('Subscripts must be positive whole numbers.',n?.[0]);a[e]=(a[e]||0)+k}if(close)fail('Missing closing parenthesis.',close);return a}return group()}
function parse(raw){const s=clean(raw),a=[...s.matchAll(/→|->/g)];if(a.length===0)return{error:'Please enter both sides of the equation.'};if(a.length!==1)return{error:'Please use exactly one reaction arrow (→, ->, or =>).'};const x=a[0],L=s.slice(0,x.index).trim(),R=s.slice(x.index+x[0].length).trim();if(!L||!R)return{error:'Please enter both sides of the equation.'};const side=t=>t.split('+').map(v=>{const z=v.trim();if(!z)throw new Error('Please enter both sides of the equation.');const m=z.match(/^(\d+)\s*(.+)$/),coef=m?+m[1]:1,f=(m?m[2]:z).trim();if(coef<=0)throw new Error('Coefficients must be positive whole numbers.');try{return{coef,f,a:formula(f)}}catch(e){throw new Error(`${e.message} Problem found: “${e.problem||f}”.`)}});try{return{left:side(L),right:side(R)}}catch(e){return{error:e.message}}}
function counts(side){const o={};for(const x of side)for(const[e,n]of Object.entries(x.a))o[e]=(o[e]||0)+n*x.coef;return o}
function elements(eq){return[...new Set([...Object.keys(counts(eq.left)),...Object.keys(counts(eq.right))])].sort()}
function solve(eq){const all=[...eq.left,...eq.right],es=elements(eq),n=all.length,m=es.length;if(n<2)return null;const A=es.map(e=>all.map((x,i)=>(i<eq.left.length?1:-1)*(x.a[e]||0))),M=A.map(r=>r.slice());let r=0,p=[];for(let c=0;c<n&&r<m;c++){let q=r;for(let k=r+1;k<m;k++)if(Math.abs(M[k][c])>Math.abs(M[q][c]))q=k;if(Math.abs(M[q][c])<1e-12)continue;[M[r],M[q]]=[M[q],M[r]];const d=M[r][c];for(let j=c;j<n;j++)M[r][j]/=d;for(let k=0;k<m;k++)if(k!==r){const f=M[k][c];if(Math.abs(f)>1e-12)for(let j=c;j<n;j++)M[k][j]-=f*M[r][j]}p.push(c);r++}for(let k=r;k<m;k++)if(M[k].some(v=>Math.abs(v)>1e-10))return null;const free=[];for(let c=0;c<n;c++)if(!p.includes(c))free.push(c);if(!free.length)return null;let ans=null,vals=Array(free.length).fill(1);function attempt(pos){if(ans)return;if(pos===free.length){const v=Array(n).fill(0);free.forEach((c,i)=>v[c]=vals[i]);for(let q=p.length-1;q>=0;q--){const c=p[q];let z=0;for(let j=c+1;j<n;j++)z+=M[q][j]*v[j];v[c]=-z}if(v.some(x=>!Number.isFinite(x)||x<=0))return;let den=1;for(const x of v){let ok=false;for(let d=1;d<=1200;d++)if(Math.abs(x*d-Math.round(x*d))<1e-8){den=den*d/gcd(den,d);ok=true;break}if(!ok)return}let co=v.map(x=>Math.round(x*den)),g=co.reduce(gcd,0)||1;co=co.map(x=>x/g);if(co.some(x=>x<=0||x>100000))return;for(let i=0;i<m;i++){let sum=0;for(let j=0;j<n;j++)sum+=A[i][j]*co[j];if(sum!==0)return}ans=co;return}for(let x=1;x<=12&&!ans;x++){vals[pos]=x;attempt(pos+1)}}attempt(0);return ans}
function eqHTML(eq,co){let i=0;const side=a=>a.map(x=>{const c=co[i++];return(c===1?'':c)+pretty(x.f)}).join(' + ');return side(eq.left)+' <span>→</span> '+side(eq.right)}
function eqText(eq,co){let i=0;const side=a=>a.map(x=>{const c=co[i++];return(c===1?'':c)+x.f}).join(' + ');return side(eq.left)+' → '+side(eq.right)}
function render(){const p=parse(input.value);out.classList.remove('hidden');if(p.error){out.innerHTML=`<div class="checker-status checker-status-error"><span>!</span><div><b>Invalid equation</b><small>${esc(p.error)}</small></div></div>`;return}const L=counts(p.left),R=counts(p.right),es=elements(p),bad=es.filter(e=>(L[e]||0)!==(R[e]||0)),balanced=!bad.length,co=balanced?null:solve(p),correct=co?`<div class="checker-section checker-correct"><div class="checker-section-title"><b>Balanced equation</b></div><div class="checker-equation">${eqHTML(p,co)}</div><div class="checker-balance-cta"><div class="checker-balance-cta-copy"><b>Want to balance it yourself?</b><p>Open the Balancer with this equation ready to edit.</p></div><a class="primary" href="index.html?equation=${encodeURIComponent(eqText(p,co))}">Open Balancer →</a></div></div>`:'';const rows=es.map(e=>`<div class="atom-row ${bad.includes(e)?'atom-row-bad':''}"><b>${e}</b><span>${L[e]||0}</span><span>${R[e]||0}</span><strong>${bad.includes(e)?'✗':'✓'}</strong></div>`).join('');out.innerHTML=`<div class="checker-status ${balanced?'checker-status-good':'checker-status-bad'}"><span>${balanced?'✓':'✗'}</span><div><b>${balanced?'Balanced':'Unbalanced equation'}</b><small>${balanced?'All atom counts match.':'One or more element totals do not match.'}</small></div></div><div class="checker-section"><div class="checker-section-title"><b>Atom count</b><span>Left · Right</span></div><div class="atom-grid"><div></div><b>Left</b><b>Right</b><div></div></div>${rows}</div>${bad.length?`<div class="checker-section checker-problems"><div class="checker-section-title"><b>Elements needing attention</b></div><div class="problem-chips">${bad.map(e=>`<span>${e}: ${L[e]||0} → ${R[e]||0}</span>`).join('')}</div></div>`:''}${correct}<div class="checker-section checker-explanation"><div class="checker-section-title"><b>Explanation</b></div><p>${balanced?'Every element has the same atom count on both sides, so no coefficient changes are needed.':'The highlighted elements have different totals. Change coefficients—not subscripts—so every element has the same total on both sides.'}</p></div>`}
btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();render()},true);
input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();render()}});
})();