(()=>{
'use strict';
const input=document.getElementById('checkInput'),btn=document.getElementById('checkBtn'),out=document.getElementById('checkResult');
if(!input||!btn||!out)return;
const cleanBtn=btn.cloneNode(true);btn.replaceWith(cleanBtn);
const symbols=new Set('H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr'.split(' '));
const norm=s=>String(s||'').replace(/[₀₁₂₃₄₅₆₇₈₉]/g,c=>'0123456789'['₀₁₂₃₄₅₆₇₈₉'.indexOf(c)]).replace(/⟶|⇒|➜|⟹|⟾|=>|->/g,'→').replace(/=(?!>)/g,'→').replace(/\s+/g,' ').trim();
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseFormula(s){s=String(s||'').replace(/\s+/g,'');let i=0;function fail(m,p){const e=new Error(m);e.problem=p||s.slice(i)||s;throw e}function group(close){const a={};while(i<s.length){if(close&&s[i]===close){i++;return a}if(s[i]===')')fail('Unexpected closing parenthesis.',')');if(s[i]==='('){i++;const g=group(')'),m=s.slice(i).match(/^\d+/),k=m?+m[0]:1;if(m)i+=m[0].length;if(k<=0)fail('Subscripts must be positive whole numbers.',m&&m[0]);for(const e in g)a[e]=(a[e]||0)+g[e]*k;continue}const m=s.slice(i).match(/^[A-Z][a-z]?/);if(!m){const t=s.slice(i);if(/^[a-z]/.test(t))fail('Invalid element symbol “'+s[i]+'”.',s[i]);fail('Invalid chemical formula near “'+t+'”.',t)}const e=m[0];if(!symbols.has(e))fail('Invalid element symbol “'+e+'”.',e);i+=e.length;const n=s.slice(i).match(/^\d+/),k=n?+n[0]:1;if(n)i+=n[0].length;if(k<=0)fail('Subscripts must be positive whole numbers.',n&&n[0]);a[e]=(a[e]||0)+k}if(close)fail('Missing closing parenthesis.',close);return a}return group()}
function parse(raw){const s=norm(raw),a=[...s.matchAll(/→/g)];if(a.length!==1)return{error:a.length===0?'Please enter both sides of the equation.':'Please use exactly one reaction arrow.'};const x=a[0],L=s.slice(0,x.index).trim(),R=s.slice(x.index+1).trim();if(!L||!R)return{error:'Please enter both sides of the equation.'};const side=t=>t.split('+').map(v=>{const z=v.trim();if(!z)throw new Error('Please enter a formula on both sides of the equation.');const m=z.match(/^(\d+)\s*(.+)$/),coef=m?+m[1]:1,f=(m?m[2]:z).trim();if(coef<=0)throw new Error('Coefficients must be positive whole numbers.');try{return{coef,f,a:parseFormula(f)}}catch(e){throw new Error(e.message+' Problem found: “'+(e.problem||f)+'”.')}});try{return{left:side(L),right:side(R)}}catch(e){return{error:e.message}}}
function counts(side){const o={};for(const x of side)for(const[e,n]of Object.entries(x.a))o[e]=(o[e]||0)+n*x.coef;return o}
function equationText(eq){const side=a=>a.map(x=>(x.coef===1?'':x.coef)+x.f).join(' + ');return side(eq.left)+' → '+side(eq.right)}
function prettyFormula(f){return esc(f).replace(/([A-Z][a-z]?)(\d+)/g,'$1<sub>$2</sub>')}
function run(){
 const p=parse(input.value);out.classList.remove('hidden');
 if(p.error){out.innerHTML='<div class="checker-status checker-status-error"><span>!</span><div><b>Invalid equation</b><small>'+esc(p.error)+'</small></div></div>';return}
 const L=counts(p.left),R=counts(p.right),es=Array.from(new Set([...Object.keys(L),...Object.keys(R)])).sort(),bad=es.filter(e=>(L[e]||0)!==(R[e]||0));
 const rows=es.map(e=>'<div class="atom-row '+(bad.includes(e)?'atom-row-bad':'')+'"><b>'+esc(e)+'</b><span>'+(L[e]||0)+'</span><span>'+(R[e]||0)+'</span><strong>'+(bad.includes(e)?'✗':'✓')+'</strong></div>').join('');
 if(!bad.length){out.innerHTML='<div class="checker-status checker-status-good"><span>✓</span><div><b>Balanced</b><small>Every element has the same number of atoms on both sides.</small></div></div><div class="checker-section"><div class="checker-section-title"><b>Atom count</b><span>Left · Right</span></div><div class="atom-grid"><div></div><b>Left</b><b>Right</b><div></div></div>'+rows+'</div><div class="checker-section checker-explanation"><div class="checker-section-title"><b>Explanation</b></div><p>The equation is balanced because all element totals match on both sides.</p></div>';return}
 const text=equationText(p);
 out.innerHTML='<div class="checker-status checker-status-bad"><span>✗</span><div><b>Unbalanced equation</b><small>One or more element totals do not match.</small></div></div><div class="checker-section"><div class="checker-section-title"><b>Atom count</b><span>Left · Right</span></div><div class="atom-grid"><div></div><b>Left</b><b>Right</b><div></div></div>'+rows+'</div><div class="checker-section checker-problems"><div class="checker-section-title"><b>Elements needing attention</b></div><div class="problem-chips">'+bad.map(e=>'<span>'+esc(e)+': '+(L[e]||0)+' → '+(R[e]||0)+'</span>').join('')+'</div></div><div class="checker-section checker-balance-cta"><div><b>Need the balanced equation?</b><small>Open the Balancer to calculate the correct coefficients and see the solution.</small></div><a class="primary checker-balance-button" href="index.html?equation='+encodeURIComponent(text)+'">Open Balancer →</a></div><div class="checker-section checker-explanation"><div class="checker-section-title"><b>Explanation</b></div><p>The highlighted elements have different totals. The equation needs coefficient changes so each element has the same total on both sides.</p></div>';
}
cleanBtn.addEventListener('click',e=>{e.preventDefault();run()});
input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();run()}});
})();