(()=>{
'use strict';
const input=document.getElementById('checkInput'),btn=document.getElementById('checkBtn'),out=document.getElementById('checkResult');
if(!input||!btn||!out)return;
const symbols=new Set('H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr'.split(' '));
const normalize=s=>String(s||'').replace(/[₀₁₂₃₄₅₆₇₈₉]/g,c=>'0123456789'['₀₁₂₃₄₅₆₇₈₉'.indexOf(c)]).replace(/⟶|⇒|➜|⟹|⟾/g,'→').replace(/=>/g,'→').replace(/=(?!>)/g,'→').replace(/\s+/g,' ').trim();
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=s=>esc(String(s||'')).replace(/([A-Z][a-z]?)(\d+)/g,'$1<sub>$2</sub>');
const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a};
const lcm=(a,b)=>Math.abs(a/gcd(a,b)*b);
function parseFormula(text){const s=String(text||'').replace(/\s+/g,'');let i=0;const fail=(message,pos=i,token='')=>{const e=new Error(message);e.problem=token||s.slice(pos);throw e};function group(close){const a={};while(i<s.length){if(close&&s[i]===close){i++;return a}if(s[i]===')')fail('Unexpected closing parenthesis.',i,')');if(s[i]==='('){i++;const g=group(')'),m=s.slice(i).match(/^\d+/),mult=m?+m[0]:1;if(m)i+=m[0].length;if(mult<=0)fail('Subscripts must be positive whole numbers.',i-1,m?.[0]);for(const e in g)a[e]=(a[e]||0)+g[e]*mult;continue}const em=s.slice(i).match(/^[A-Z][a-z]?/);if(!em){const token=s.slice(i);if(/^[a-z]/.test(token))fail(`Invalid element symbol “${s[i]}”.`,i,s[i]);fail(`Invalid formula near “${token}”.`,i,token)}const e=em[0];if(!symbols.has(e))fail(`Invalid element symbol “${e}”.`,i,e);i+=e.length;const n=s.slice(i).match(/^\d+/),mult=n?+n[0]:1;if(n)i+=n[0].length;if(mult<=0)fail('Subscripts must be positive whole numbers.',i-(n?.[0]?.length||0),n?.[0]);a[e]=(a[e]||0)+mult}if(close)fail('Missing closing parenthesis.',s.length,close);return a}return group()}
function parseEquation(raw){const s=normalize(raw),ar=[...s.matchAll(/→|->/g)];if(ar.length===0)return{error:'Please enter both sides of the equation.'};if(ar.length!==1)return{error:'Please use exactly one reaction arrow (→, ->, or =>).'};const a=ar[0],L=s.slice(0,a.index).trim(),R=s.slice(a.index+a[0].length).trim();if(!L||!R)return{error:'Please enter both sides of the equation.'};function side(t){return t.split('+').map(v=>{const z=v.trim();if(!z)throw new Error('Please enter a formula on both sides of the equation.');const m=z.match(/^(\d+)\s*(.+)$/),coef=m?+m[1]:1,formula=(m?m[2]:z).trim();if(coef<=0)throw new Error('Coefficients must be positive whole numbers.');try{return{coef,formula,atoms:parseFormula(formula)}}catch(e){throw new Error(`${e.message} Problem found: “${e.problem||formula}”.`)}})}try{return{left:side(L),right:side(R)}}catch(e){return{error:e.message}}}
function counts(side){const c={};for(const item of side)for(const[e,n]of Object.entries(item.atoms))c[e]=(c[e]||0)+n*item.coef;return c}
function allElements(eq){return[...new Set([...Object.keys(counts(eq.left)),...Object.keys(counts(eq.right))])].sort()}
function balance(eq){const all=[...eq.left,...eq.right],els=allElements(eq),n=all.length,m=els.length;if(n<2)return null;const A=els.map(e=>all.map((x,i)=>(i<eq.left.length?1:-1)*(x.atoms[e]||0))),rows=A.map(r=>r.map(Number));let r=0,p=[];for(let c=0;c<n&&r<m;c++){let q=r;for(let k=r+1;k<m;k++)if(Math.abs(rows[k][c])>Math.abs(rows[q][c]))q=k;if(Math.abs(rows[q][c])<1e-12)continue;[rows[r],rows[q]]=[rows[q],rows[r]];const d=rows[r][c];for(let j=c;j<n;j++)rows[r][j]/=d;for(let k=0;k<m;k++)if(k!==r){const f=rows[k][c];if(Math.abs(f)>1e-12)for(let j=c;j<n;j++)rows[k][j]-=f*rows[r][j]}p.push(c);r++}for(let k=r;k<m;k++)if(rows[k].some(x=>Math.abs(x)>1e-10))return null;const free=[];for(let c=0;c<n;c++)if(!p.includes(c))free.push(c);if(!free.length)return null;let ans=null,vals=Array(free.length).fill(1);function attempt(pos){if(ans)return;if(pos===free.length){const v=Array(n).fill(0);free.forEach((c,i)=>v[c]=vals[i]);for(let q=p.length-1;q>=0;q--){const c=p[q];let z=0;for(let j=c+1;j<n;j++)z+=rows[q][j]*v[j];v[c]=-z}if(v.some(x=>!Number.isFinite(x)||x<=1e-10))return;let den=1;for(const x of v){let found=false;for(let d=1;d<=1200;d++)if(Math.abs(x*d-Math.round(x*d))<1e-8){den=lcm(den,d);found=true;break}if(!found)return}let co=v.map(x=>Math.round(x*den)),g=co.reduce(gcd,0);if(g)co=co.map(x=>x/g);if(co.some(x=>x<=0||x>100000))return;for(let i=0;i<m;i++){let sum=0;for(let j=0;j<n;j++)sum+=A[i][j]*co[j];if(sum!==0)return}ans=co;return}for(let x=1;x<=12&&!ans;x++){vals[pos]=x;attempt(pos+1)}}attempt(0);return ans}
function formatEq(eq,co){let i=0;const side=a=>a.map(x=>{const c=co[i++];return `${c===1?'':c}${pretty(x.formula)}`}).join(' + ');return `${side(eq.left)} <span class="checker-arrow">→</span> ${side(eq.right)}`}
function plainEq(eq,co){let i=0;const side=a=>a.map(x=>{const c=co[i++];return `${c===1?'':c}${x.formula}`}).join(' + ');return `${side(eq.left)} → ${side(eq.right)}`}
function render(){const p=parseEquation(input.value);out.classList.remove('hidden');if(p.error){out.innerHTML=`<div class="checker-status checker-status-error"><span>!</span><div><b>Invalid equation</b><small>${esc(p.error)}</small></div></div>`;return}const L=counts(p.left),R=counts(p.right),els=allElements(p),bad=els.filter(e=>(L[e]||0)!==(R[e]||0)),solved=bad.length?balance(p):null,balanced=!bad.length;const rows=els.map(e=>`<div class="atom-row ${bad.includes(e)?'atom-row-bad':''}"><b>${esc(e)}</b><span>${L[e]||0}</span><span>${R[e]||0}</span><strong>${bad.includes(e)?'✗':'✓'}</strong></div>`).join('');let correct='';if(solved){correct=`<div class="checker-section checker-correct"><div class="checker-section-title"><b>Balanced equation</b></div><div class="checker-equation">${formatEq(p,solved)}</div><div class="checker-balance-cta"><div class="checker-balance-cta-copy"><b>Want to balance it yourself?</b><p>Open the Balancer with this equation ready to edit.</p></div><a class="primary" href="index.html?equation=${encodeURIComponent(plainEq(p,solved))}">Open Balancer →</a></div></div>`}
const explain=balanced?'Every element has the same atom count on both sides, so no coefficient changes are needed.':'The highlighted elements have different totals. Change coefficients—not subscripts—so each element has the same total on both sides.';
out.innerHTML=`<div class="checker-status ${balanced?'checker-status-good':'checker-status-bad'}"><span>${balanced?'✓':'✗'}</span><div><b>${balanced?'Balanced':'Unbalanced equation'}</b><small>${balanced?'All atom counts match.':'One or more element totals do not match.'}</small></div></div><div class="checker-section"><div class="checker-section-title"><b>Atom count</b><span>Left · Right</span></div><div class="atom-grid"><div></div><b>Left</b><b>Right</b><div></div></div>${rows}</div>${bad.length?`<div class="checker-section checker-problems"><div class="checker-section-title"><b>Elements needing attention</b></div><div class="problem-chips">${bad.map(e=>`<span>${esc(e)}: ${L[e]||0} → ${R[e]||0}</span>`).join('')}</div></div>`:''}${correct}<div class="checker-section checker-explanation"><div class="checker-section-title"><b>Explanation</b></div><p>${explain}</p></div>`}
btn.addEventListener('click',e=>{e.preventDefault();render()});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();render()}});
})();