(()=>{
'use strict';
const KEY='chemistryLanguage';
const LANG={en:{dir:'ltr',label:'English'},ar:{dir:'rtl',label:'العربية'},he:{dir:'rtl',label:'עברית'}};
const EXTRA={Language:['اللغة','שפה'],Learn:['تعلّم','למידה'],Quiz:['اختبار','חידון'],Challenges:['التحديات','אתגרים'],Balancer:['موازنة المعادلات','איזון משוואות'],Checker:['التحقق','בדיקה'],Account:['الحساب','חשבון'],'👤 Account':['👤 الحساب','👤 חשבון'],Dark:['داكن','כהה'],Light:['فاتح','בהיר']};
const TITLES={'Chemistry Equations — Balancer':['معادلات الكيمياء — الموازنة','משוואות כימיות — איזון'],'Practice & Quiz — Chemistry Equations':['تدريب واختبار — معادلات الكيمياء','תרגול וחידון — משוואות כימיות'],'Challenges — Chemistry Equations':['التحديات — معادلات الكيمياء','אתגרים — משוואות כימיות'],'Checker — Chemistry Equations':['التحقق — معادلات الكيمياء','בדיקה — משוואות כימיות'],'Profile — Chemistry Equations':['الملف الشخصي — معادلات الكيمياء','פרופיל — משוואות כימיות'],'Chemistry Equations — Learn':['معادلات الكيمياء — تعلّم','משוואות כימיות — למידה'],'Beginner Chemistry Lessons — Chemistry Equations':['دروس الكيمياء للمبتدئين — معادلات الكيمياء','שיעורי כימיה למתחילים — משוואות כימיות'],'Intermediate Chemistry Lessons — Chemistry Equations':['دروس الكيمياء المتوسطة — معادلات الكيمياء','שיעורי כימיה בינוניים — משוואות כימיות'],'Advanced Chemistry Lessons — Chemistry Equations':['دروس الكيمياء المتقدمة — معادلات الكيمياء','שיעורי כימיה מתקדמים — משוואות כימיות'],'Quiz — Chemistry Equations':['اختبار — معادلات الكيمياء','חידון — משוואות כימיות'],'Chemistry Equations — Admin':['معادلات الكيمياء — الإدارة','משוואות כימיות — ניהול']};
let dict={...(window.ChemistryTranslations||{}),...EXTRA};
const reverse=new Map();
const norm=v=>String(v??'').replace(/\s+/g,' ').trim();
const currentLang=()=>{try{const v=localStorage.getItem(KEY);return LANG[v]?v:'en'}catch{return'en'}};
const index=l=>l==='ar'?0:1;
const rebuild=()=>{reverse.clear();for(const [k,p] of Object.entries(dict)){if(p?.[0])reverse.set(norm(p[0]),k);if(p?.[1])reverse.set(norm(p[1]),k)}};
const source=v=>{const n=norm(v);return dict[n]?n:(reverse.get(n)||n)};
const translated=(k,l=currentLang())=>{if(!k||l==='en')return k;const p=dict[k];return p?.[index(l)]||k};
function applyShell(){const l=currentLang(),rtl=l!=='en';document.documentElement.lang=l;document.documentElement.dir=rtl?'rtl':'ltr';document.body?.classList.toggle('is-rtl-language',rtl);const top=document.querySelector('.topbar'),nav=document.querySelector('.main-nav');if(top)top.setAttribute('dir','ltr');if(nav){nav.setAttribute('dir','ltr');nav.querySelectorAll('a').forEach(a=>a.setAttribute('dir',rtl?'rtl':'ltr'))}const brand=document.querySelector('.brand');if(brand){const text=l==='ar'?'معادلات الكيمياء':l==='he'?'משוואות כימיות':'Chemistry Equations';if(brand.dataset.i18nBrand!==l){brand.textContent='⚗ '+text;brand.dataset.i18nBrand=l}}const title=norm(document.title);for(const [en,p] of Object.entries(TITLES)){if(title===en||title===norm(p[0])||title===norm(p[1])){document.title=l==='en'?en:p[index(l)];break}}let box=document.getElementById('site-language-control');if(top&&!box){box=document.createElement('label');box.id='site-language-control';box.className='site-language-control';box.innerHTML='<span class="site-language-icon" aria-hidden="true">🌐</span><span class="site-language-label">Language</span><select id="site-language-select" aria-label="Language"><option value="en">English</option><option value="ar">العربية</option><option value="he">עברית</option></select>';top.appendChild(box);box.querySelector('select').addEventListener('change',e=>{const v=LANG[e.target.value]?e.target.value:'en';try{localStorage.setItem(KEY,v)}catch{}refresh();window.dispatchEvent(new CustomEvent('chemistryLanguageChanged',{detail:{language:v}}))})}const select=document.getElementById('site-language-select');if(select)select.value=l;const label=document.querySelector('.site-language-label');if(label)label.textContent=l==='ar'?'اللغة':l==='he'?'שפה':'Language'}
function refresh(){applyShell();rebuild();const l=currentLang();const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let count=0,n;while(count<40&&(n=walker.nextNode())){const p=n.parentElement;if(p&&!p.closest('script,style,noscript,textarea,code,pre,.brand,[data-no-translate],.equation,.chemical-equation,.formula,.math,[data-equation],[data-chemical],canvas,#site-language-control')){const raw=norm(n.nodeValue);if(raw){const s=source(raw),out=translated(s,l);if(out!==raw)n.nodeValue=n.nodeValue.replace(raw,out)}}count++}}
const api={lang:currentLang,t:(en,ar,he)=>{const l=currentLang();return l==='ar'&&ar!=null?ar:l==='he'&&he!=null?he:translated(source(en),l)},refresh,apply:refresh,setLanguage:l=>{if(!LANG[l])return;try{localStorage.setItem(KEY,l)}catch{}refresh();window.dispatchEvent(new CustomEvent('chemistryLanguageChanged',{detail:{language:l}}))}};
window.ChemistryI18n=api;window.ChemLang=api;window.dispatchEvent(new Event('chemistryI18nReady'));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh,{once:true});else refresh();
})();
