(()=>{
const KEY='chemistryLanguage';
const LANGS={en:{label:'English',dir:'ltr'},ar:{label:'العربية',dir:'rtl'},he:{label:'עברית',dir:'rtl'}};
const T={
'Learn':{ar:'تعلّم',he:'למידה'},'Quiz':{ar:'اختبار',he:'חידון'},'Challenges':{ar:'التحديات',he:'אתגרים'},'Balancer':{ar:'موازنة المعادلات',he:'מאזן משוואות'},'Checker':{ar:'التحقق',he:'בדיקה'},'Account':{ar:'الحساب',he:'חשבון'},
'Create account':{ar:'إنشاء حساب',he:'יצירת חשבון'},'Learning':{ar:'التعلّم',he:'למידה'},'Practice':{ar:'تدريب',he:'תרגול'},'Beginner':{ar:'مبتدئ',he:'מתחילים'},'Intermediate':{ar:'متوسط',he:'בינוני'},'Advanced':{ar:'متقدم',he:'מתקדם'},
'Balance equations.':{ar:'وازن المعادلات.',he:'אזנו משוואות.'},'Understand why.':{ar:'افهم السبب.',he:'הבינו מדוע.'},'Enter a chemical equation and get the balanced result immediately, with optional step-by-step and algebra explanations.':{ar:'أدخل معادلة كيميائية واحصل فورًا على المعادلة الموزونة، مع إمكانية عرض الحل خطوة بخطوة وشرح جبري.',he:'הזינו משוואה כימית וקבלו מיד את התוצאה המאוזנת, עם אפשרות להסבר שלב אחר שלב ולהסבר אלגברי.'},
'Conservation of atoms':{ar:'حفظ الذرات',he:'שימור האטומים'},'The number of each element must be the same on both sides.':{ar:'يجب أن يكون عدد ذرات كل عنصر متساويًا على الجانبين.',he:'מספר האטומים של כל יסוד חייב להיות זהה בשני הצדדים.'},
'Balance an equation':{ar:'وازن معادلة',he:'אזנו משוואה'},'Try an example':{ar:'جرّب مثالًا',he:'נסו דוגמה'},'Balance':{ar:'وازن',he:'אזן'},'Chemical equation':{ar:'المعادلة الكيميائية',he:'משוואה כימית'},'Handwriting input':{ar:'الإدخال بالكتابة اليدوية',he:'קלט בכתב יד'},'Recognizes subscripts, coefficients and reaction arrows. You can correct the recognized equation before balancing.':{ar:'يتعرّف على الأرقام السفلية والمعاملات وأسهم التفاعل. يمكنك تصحيح المعادلة التي تم التعرّف عليها قبل موازنتها.',he:'מזהה מספרים תחתיים, מקדמים וחיצי תגובה. ניתן לתקן את המשוואה שזוהתה לפני האיזון.'},'Clear':{ar:'مسح',he:'ניקוי'},'Undo':{ar:'تراجع',he:'בטל'},'Redo':{ar:'إعادة',he:'בצע שוב'},'Eraser':{ar:'ممحاة',he:'מחק'},'Recognize':{ar:'تعرّف',he:'זיהוי'},'Draw an equation, then tap Recognize.':{ar:'ارسم معادلة، ثم اضغط على «تعرّف».',he:'ציירו משוואה ולאחר מכן לחצו על «זיהוי».'},'Correct the recognized equation before balancing:':{ar:'صحّح المعادلة التي تم التعرّف عليها قبل الموازنة:',he:'תקנו את המשוואה שזוהתה לפני האיזון:'},'Balance corrected equation':{ar:'وازن المعادلة المصححة',he:'אזנו את המשוואה המתוקנת'},
'Practice at':{ar:'تدرّب',he:'תרגלו'},'your pace.':{ar:'بالوتيرة التي تناسبك.',he:'בקצב שלכם.'},'Choose difficulty and mode, generate unlimited fresh quizzes, and track your performance.':{ar:'اختر مستوى الصعوبة وطريقة التدريب، وأنشئ اختبارات جديدة بلا حدود، وتابع أداءك.',he:'בחרו רמת קושי ואופן תרגול, צרו חידונים חדשים ללא הגבלה ועקבו אחר הביצועים שלכם.'},'Choose a level':{ar:'اختر المستوى',he:'בחרו רמה'},'Easy':{ar:'سهل',he:'קל'},'Medium':{ar:'متوسط',he:'בינוני'},'Hard':{ar:'صعب',he:'קשה'},'Basics and simple equations':{ar:'الأساسيات والمعادلات البسيطة',he:'יסודות ומשוואות פשוטות'},'Groups, parentheses and more steps':{ar:'المجموعات والأقواس والمزيد من الخطوات',he:'קבוצות, סוגריים ושלבים נוספים'},'Combustion and complex reactions':{ar:'الاحتراق والتفاعلات المعقدة',he:'בעירה ותגובות מורכבות'},'How do you want to practice?':{ar:'كيف تريد أن تتدرّب؟',he:'איך תרצו לתרגל?'},'Untimed':{ar:'بدون مؤقت',he:'ללא הגבלת זמן'},'Timed · 5 minutes':{ar:'مؤقت · 5 دقائق',he:'מתוזמן · 5 דקות'},'Challenge · 60 seconds':{ar:'تحدٍّ · 60 ثانية',he:'אתגר · 60 שניות'},'Start new quiz':{ar:'ابدأ اختبارًا جديدًا',he:'התחילו חידון חדש'},'New quiz':{ar:'اختبار جديد',he:'חידון חדש'},'Unlimited fresh quizzes. Your mistakes are saved for review.':{ar:'اختبارات جديدة بلا حدود. يتم حفظ أخطائك للمراجعة.',he:'חידונים חדשים ללא הגבלה. הטעויות שלכם נשמרות לעיון.'},'Retry mistakes only':{ar:'أعد الأخطاء فقط',he:'תרגלו רק טעויות'},'Question history':{ar:'سجل الأسئلة',he:'היסטוריית שאלות'},'YOUR STATS':{ar:'إحصاءاتك',he:'הסטטיסטיקה שלך'},'Quiz history':{ar:'سجل الاختبارات',he:'היסטוריית חידונים'},'Best results, accuracy and recurring mistakes.':{ar:'أفضل النتائج والدقة والأخطاء المتكررة.',he:'התוצאות הטובות ביותר, דיוק וטעויות חוזרות.'},
'Practice solo.':{ar:'تدرّب بمفردك.',he:'תרגלו לבד.'},'Challenge someone.':{ar:'تحدَّ شخصًا آخر.',he:'אתגרו מישהו.'},'Solo Practice':{ar:'تدريب فردي',he:'תרגול אישי'},'Challenge':{ar:'تحدٍّ',he:'אתגר'},'Practice at your own pace with Easy, Medium and Hard quizzes.':{ar:'تدرّب بالوتيرة التي تناسبك باستخدام اختبارات سهلة ومتوسطة وصعبة.',he:'תרגלו בקצב שלכם עם חידונים קלים, בינוניים וקשים.'},'Compete head-to-head with another player in a live timed match.':{ar:'تنافس مباشرةً مع لاعب آخر في مباراة محددة الوقت.',he:'התחרו ראש בראש מול שחקן אחר במשחק חי עם הגבלת זמן.'},'Same questions • 60-second challenge • live progress • final comparison':{ar:'الأسئلة نفسها • تحدٍّ لمدة 60 ثانية • تقدم مباشر • مقارنة نهائية',he:'אותן שאלות • אתגר של 60 שניות • התקדמות בזמן אמת • השוואה סופית'},'Random opponent':{ar:'خصم عشوائي',he:'יריב אקראי'},'Invite a specific player':{ar:'دعوة لاعب محدد',he:'הזמנת שחקן מסוים'},'Join with challenge code':{ar:'انضم برمز التحدي',he:'הצטרפות באמצעות קוד אתגר'},'Match with an available player.':{ar:'طابقك مع لاعب متاح.',he:'התאימו אתכם לשחקן זמין.'},'Specific player':{ar:'لاعب محدد',he:'שחקן מסוים'},'Create a private room and send the player your challenge code or link.':{ar:'أنشئ غرفة خاصة وأرسل للاعب رمز التحدي أو الرابط.',he:'צרו חדר פרטי ושלחו לשחקן את קוד האתגר או הקישור.'},'Same questions':{ar:'الأسئلة نفسها',he:'אותן שאלות'},'Both players receive the identical question set.':{ar:'يحصل كلا اللاعبين على مجموعة الأسئلة نفسها.',he:'שני השחקנים מקבלים בדיוק את אותה קבוצת שאלות.'},'Live competition':{ar:'منافسة مباشرة',he:'תחרות בזמן אמת'},'Timer and progress update while you solve.':{ar:'يتم تحديث المؤقت والتقدم أثناء الحل.',he:'הטיימר וההתקדמות מתעדכנים בזמן הפתרון.'},'Live score':{ar:'النتيجة المباشرة',he:'ניקוד בזמן אמת'},'Track your progress during the match.':{ar:'تابع تقدمك أثناء المباراة.',he:'עקבו אחר ההתקדמות שלכם במהלך המשחק.'},'Final comparison':{ar:'المقارنة النهائية',he:'השוואה סופית'},'See both scores and who won after a real challenge.':{ar:'شاهد نتيجتي اللاعبين ومن فاز بعد انتهاء التحدي.',he:'ראו את שתי התוצאות ומי ניצח לאחר אתגר אמיתי.'},'How inviting works':{ar:'كيفية عمل الدعوة',he:'כיצד פועלת ההזמנה'},'Fastest solvers':{ar:'أسرع الحُلال',he:'הפותרים המהירים ביותר'},'Ranked by challenge solve time.':{ar:'الترتيب حسب زمن حل التحدي.',he:'הדירוג נקבע לפי זמן פתרון האתגר.'},'Refresh':{ar:'تحديث',he:'רענון'},
'Check your':{ar:'تحقق من',he:'בדקו את'},'equation.':{ar:'معادلتك.',he:'המשוואה שלכם.'},"Enter your balanced equation and we'll check every element and coefficient.":{ar:'أدخل معادلتك الموزونة وسنتحقق من كل عنصر وكل معامل.',he:'הזינו את המשוואה המאוזנת שלכם ונבדוק כל יסוד וכל מקדם.'},'Your equation':{ar:'معادلتك',he:'המשוואה שלכם'},'Check equation':{ar:'تحقق من المعادلة',he:'בדקו משוואה'},'What gets checked?':{ar:'ما الذي يتم التحقق منه؟',he:'מה נבדק?'},'Same elements on both sides':{ar:'العناصر نفسها على الجانبين',he:'אותם יסודות בשני הצדדים'},'Same number of atoms for every element':{ar:'العدد نفسه من الذرات لكل عنصر',he:'אותו מספר אטומים מכל יסוד'},'Valid chemical formulas':{ar:'الصيغ الكيميائية الصحيحة',he:'נוסחאות כימיות תקינות'},'Simplest whole-number coefficients':{ar:'أبسط معاملات بأعداد صحيحة',he:'מקדמים שלמים ביחס המצומצם ביותר'},'Need help?':{ar:'تحتاج إلى مساعدة؟',he:'זקוקים לעזרה?'},"Go back to the balancer to get the correct coefficients, or open the learning guide for the method.":{ar:'ارجع إلى أداة الموازنة للحصول على المعاملات الصحيحة، أو افتح دليل التعلّم لمعرفة الطريقة.',he:'חזרו למאזן כדי לקבל את המקדמים הנכונים, או פתחו את מדריך הלמידה כדי ללמוד את השיטה.'},'Balance an equation':{ar:'وازن معادلة',he:'אזנו משוואה'},'Learn how':{ar:'تعلّم الطريقة',he:'למדו כיצד'},
'Balancing checklist':{ar:'قائمة تحقق للموازنة',he:'רשימת בדיקה לאיזון'},'Correct element symbols':{ar:'رموز العناصر الصحيحة',he:'סמלי יסודות נכונים'},'Correct chemical formulas and subscripts':{ar:'الصيغ الكيميائية والأرقام السفلية الصحيحة',he:'נוסחאות כימיות ומספרים תחתיים נכונים'},'Correct diatomic formulas when applicable':{ar:'الصيغ الصحيحة للعناصر ثنائية الذرة عند الحاجة',he:'נוסחאות נכונות של יסודות דו-אטומיים כאשר רלוונטי'},'Count atoms on both sides':{ar:'عُدّ الذرات على الجانبين',he:'ספרו אטומים בשני הצדדים'},'Add coefficients instead of changing formulas':{ar:'أضف معاملات بدلًا من تغيير الصيغ',he:'הוסיפו מקדמים במקום לשנות נוסחאות'},'Recount every element':{ar:'أعد عدّ كل عنصر',he:'ספרו מחדש כל יסוד'},'Use the smallest whole-number ratio':{ar:'استخدم أصغر نسبة من أعداد صحيحة',he:'השתמשו ביחס השלם הקטן ביותר'},
'Privacy & Security':{ar:'الخصوصية والأمان',he:'פרטיות ואבטחה'},'Change password':{ar:'تغيير كلمة المرور',he:'שינוי סיסמה'},'Password recovery':{ar:'استرداد كلمة المرور',he:'שחזור סיסמה'},'Recovery code':{ar:'رمز الاسترداد',he:'קוד שחזור'},'Sign out':{ar:'تسجيل الخروج',he:'התנתקות'},'Remember me':{ar:'تذكّرني',he:'זכור אותי'},
'What does the arrow in a chemical equation show?':{ar:'ماذا يُظهر السهم في المعادلة الكيميائية؟',he:'מה מראה החץ במשוואה כימית?'},'What are the substances on the left called?':{ar:'ماذا تُسمّى المواد الموجودة على اليسار؟',he:'כיצד נקראים החומרים שבצד שמאל?'},'What are the substances on the right called?':{ar:'ماذا تُسمّى المواد الموجودة على اليمين؟',he:'כיצד נקראים החומרים שבצד ימין?'},
'Chemistry Equations':{ar:'المعادلات الكيميائية',he:'משוואות כימיות'},'Loading…':{ar:'جارٍ التحميل…',he:'טוען…'},'Loading profile…':{ar:'جارٍ تحميل الملف الشخصي…',he:'טוען את הפרופיל…'},'Learn • Quiz • Challenges • Balance • Check':{ar:'تعلّم • اختبار • تحديات • موازنة • تحقق',he:'למידה • חידון • אתגרים • איזון • בדיקה'}
};
function lang(){return localStorage.getItem(KEY)||'en'}
function tr(s,l){return l==='en'?s:(T[s]?.[l]||s)}
function translate(root,l){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];
 while(walker.nextNode()) nodes.push(walker.currentNode);
 nodes.forEach(n=>{if(!n.parentElement||n.parentElement.closest('script,style,code,textarea,.equation'))return;const raw=n.nodeValue;const key=raw.trim();if(T[key]?.[l])n.nodeValue=raw.replace(key,T[key][l])});
 root.querySelectorAll('input[placeholder],input[aria-label],textarea[placeholder],textarea[aria-label]').forEach(e=>{['placeholder','aria-label'].forEach(a=>{if(e.getAttribute(a)){const k=e.getAttribute(a).trim();if(T[k]?.[l])e.setAttribute(a,T[k][l])}})});
 root.querySelectorAll('title').forEach(e=>{const s=e.textContent;for(const k in T)if(s.includes(k))e.textContent=s.replace(k,tr(k,l))});
}
function checklist(l){const lines=['Correct element symbols','Correct chemical formulas and subscripts','Correct diatomic formulas when applicable','Count atoms on both sides','Add coefficients instead of changing formulas','Recount every element','Use the smallest whole-number ratio'];return lines.map(x=>'✓ '+tr(x,l)).join('<br>')}
function apply(){const l=lang(),m=LANGS[l]||LANGS.en;document.documentElement.lang=l;document.documentElement.dir=m.dir;document.body?.classList.toggle('rtl',m.dir==='rtl');translate(document.body,l);document.querySelectorAll('.i18n-checklist').forEach(e=>e.innerHTML=checklist(l));}
window.addEventListener('DOMContentLoaded',()=>{apply();setTimeout(apply,150);setTimeout(apply,600);});
window.addEventListener('languagechange',apply);window.translateSite=apply;
})();
