(()=>{
'use strict';
const KEY='chemistryLanguage';
const L={en:{dir:'ltr'},ar:{dir:'rtl'},he:{dir:'rtl'}};
const T={
'Learn':{ar:'تعلّم',he:'למידה'},'Quiz':{ar:'اختبار',he:'חידון'},'Challenges':{ar:'التحديات',he:'אתגרים'},'Balancer':{ar:'موازنة المعادلات',he:'איזון משוואות'},'Checker':{ar:'التحقق',he:'בדיקה'},'Account':{ar:'الحساب',he:'חשבון'},
'3 · BALANCER':{ar:'3 · الموازنة',he:'3 · איזון משוואות'},'Balance equations.':{ar:'وازن المعادلات.',he:'אזנו משוואות.'},'Understand why.':{ar:'افهم السبب.',he:'הבינו מדוע.'},'Conservation of atoms':{ar:'حفظ الذرات',he:'שימור האטומים'},'The number of each element must be the same on both sides.':{ar:'يجب أن يكون عدد ذرات كل عنصر متساويًا على جانبي المعادلة.',he:'מספר האטומים של כל יסוד חייב להיות זהה בשני צדי המשוואה.'},'BALANCE':{ar:'موازنة',he:'איזון'},'Balance an equation':{ar:'وازن معادلة',he:'אזנו משוואה'},'Try an example':{ar:'جرّب مثالًا',he:'נסו דוגמה'},'Balance':{ar:'وازن',he:'אזן'},
'Handwriting input':{ar:'الإدخال بالكتابة اليدوية',he:'קלט בכתב יד'},'Clear':{ar:'مسح',he:'ניקוי'},'Undo':{ar:'تراجع',he:'ביטול'},'Redo':{ar:'إعادة',he:'ביצוע מחדש'},'Eraser':{ar:'ممحاة',he:'מחק'},'Recognize':{ar:'تعرّف',he:'זיהוי'},'Draw an equation, then tap Recognize.':{ar:'ارسم معادلة، ثم اضغط على «تعرّف».',he:'ציירו משוואה ולאחר מכן לחצו על «זיהוי».'},
'Easy':{ar:'سهل',he:'קל'},'Medium':{ar:'متوسط',he:'בינוני'},'Hard':{ar:'صعب',he:'קשה'},'Choose how to play':{ar:'اختر طريقة اللعب',he:'בחרו איך לשחק'},'Choose how to practice':{ar:'اختر طريقة التدريب',he:'בחרו איך לתרגל'},'Untimed':{ar:'بدون مؤقت',he:'ללא הגבלת זמן'},'Timed · 5 minutes':{ar:'مؤقت · 5 دقائق',he:'מתוזמן · 5 דקות'},'Challenge · 60 seconds':{ar:'تحدٍ · 60 ثانية',he:'אתגר · 60 שניות'},
'Solo Practice':{ar:'التدريب الفردي',he:'תרגול אישי'},'Multiplayer Challenge':{ar:'تحدي متعدد اللاعبين',he:'אתגר רב־משתתפים'},'Random opponent':{ar:'خصم عشوائي',he:'יריב אקראי'},'Invite a specific player':{ar:'دعوة لاعب محدد',he:'הזמנת שחקן מסוים'},'Join with challenge code':{ar:'الانضمام برمز التحدي',he:'הצטרפות באמצעות קוד אתגר'},'Fastest solvers':{ar:'أسرع المتسابقين',he:'הפותרים המהירים ביותר'},
'Solo Practice and Multiplayer Challenge are separate experiences. In a challenge, both players get the same questions and race against the clock.':{ar:'التدريب الفردي والتحدي متعدد اللاعبين تجربتان منفصلتان. في التحدي، يحصل كلا اللاعبين على الأسئلة نفسها ويتنافسان ضد الساعة.',he:'תרגול אישי ואתגר רב־משתתפים הם שתי חוויות נפרדות. באתגר, שני השחקנים מקבלים את אותן שאלות ומתחרים נגד השעון.'},
'What gets checked?':{ar:'ما الذي يتم التحقق منه؟',he:'מה נבדק؟'},'Same elements on both sides':{ar:'العناصر نفسها على الجانبين',he:'אותם יסודות בשני הצדדים'},'Same number of atoms for every element':{ar:'العدد نفسه من الذرات لكل عنصر',he:'אותו מספר אטומים לכל יסוד'},'Valid chemical formulas':{ar:'الصيغ الكيميائية الصحيحة',he:'נוסחאות כימיות תקינות'},'Simplest whole-number coefficients':{ar:'أبسط معاملات بأعداد صحيحة',he:'המקדמים השלמים הקטנים ביותר'},'Check your equation.':{ar:'تحقق من معادلتك.',he:'בדקו את המשוואה שלכם.'},'Check equation':{ar:'تحقق من المعادلة',he:'בדקו את המשוואה'}
};
function install(){let old=document.getElementById('site-language-selector');if(old)return old;let s=document.createElement('select');s.id='site-language-selector';s.innerHTML='<option value="en">English</option><option value="ar">العربية</option><option value="he">עברית</option>';s.value=localStorage.getItem(KEY)||'en';s.addEventListener('change',()=>{localStorage.setItem(KEY,s.value);apply(s.value)});Object.assign(s.style,{position:'fixed',top:'12px',right:'12px',zIndex:'2147483647',padding:'7px 10px',direction:'ltr'});document.body.appendChild(s);return s}
function apply(lang){if(!L[lang])lang='en';document.documentElement.lang=lang;document.documentElement.dir=L[lang].dir;document.body.dir=L[lang].dir;document.body.classList.toggle('rtl-language',lang!=='en');document.querySelectorAll('[data-i18n]').forEach(e=>{let k=e.dataset.i18n;if(T[k])e.textContent=lang==='en'?k:T[k][lang]||k});document.querySelectorAll('body *').forEach(e=>{if(e.children.length)return;if(e.closest('input,textarea,canvas,code,pre,.equation,.chemical-equation,.formula,[data-equation],.math'))return;let k=e.dataset.langOriginal;if(!k){k=e.textContent.trim();if(!k||!T[k])return;e.dataset.langOriginal=k}e.textContent=lang==='en'?k:(T[k][lang]||k)});document.querySelectorAll('.equation,.chemical-equation,.formula,[data-equation],.math').forEach(e=>{e.dir='ltr';e.style.direction='ltr';e.style.textAlign='center'});install().value=lang}
function init(){let lang=localStorage.getItem(KEY)||'en';install();apply(lang)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
