(()=>{
'use strict';
const KEY='chemistryLanguage';
const RTL=new Set(['ar','he']);
const T={
'Learn':['تعلّم','למידה'],'Quiz':['اختبار','חידון'],'Challenges':['التحديات','אתגרים'],'Balancer':['موازنة المعادلات','איזון משוואות'],'Checker':['التحقق','בדיקה'],'Account':['الحساب','חשבון'],
'Language':['اللغة','שפה'],'English':['English','English'],'العربية':['العربية','العربية'],'עברית':['עברית','עברית'],
'01 · LEARNING GUIDE':['٠١ · دليل التعلّم','01 · מדריך למידה'],'LEARNING GUIDE':['دليل التعلّم','מדריך למידה'],
'Learn chemistry':['تعلّم الكيمياء','למדו כימיה'],'step by step.':['خطوة بخطوة.','שלב אחר שלב.'],'Mini-course structure':['هيكل الدورة المصغّرة','מבנה הקורס הקצר'],'Concept → Worked example → Practice → Next lesson':['مفهوم ← مثال محلول ← تدريب ← الدرس التالي','מושג ← דוגמה פתורה ← תרגול ← השיעור הבא'],
'COURSE CURRICULUM':['منهج الدورة','תוכנית הלימודים'],'What you will learn':['ما الذي ستتعلمه','מה תלמדו'],'Follow the paths in order. Each detailed lesson page contains explanations, worked examples where useful, and practice questions.':['اتبع المسارات بالترتيب. تحتوي كل صفحة درس مفصلة على شروحات وأمثلة محلولة عند الحاجة وأسئلة تدريب.','עקבו אחר המסלולים לפי הסדר. כל שיעור מפורט כולל הסברים, דוגמאות פתורות כשצריך ושאלות תרגול.'],
'FOUNDATIONS':['الأساسيات','יסודות'],'FORMULAS':['الصيغ','נוסחאות'],'ELEMENTAL FORMS':['الأشكال العنصرية','צורות יסוד'],'INTERMEDIATE':['المتوسط','ביניים'],'REACTION TYPES':['أنواع التفاعلات','סוגי תגובות'],'CONFIDENCE':['الثقة','ביטחון'],
'Conservation of mass':['حفظ الكتلة','שימור המסה'],'Understand why atoms are conserved and why balancing is required.':['افهم لماذا تُحفظ الذرات ولماذا نحتاج إلى الموازنة.','הבינו מדוע האטומים נשמרים ומדוע יש צורך באיזון.'],'Reactants and products':['المتفاعلات والنواتج','מגיבים ותוצרים'],'Counting atoms':['عدّ الذرات','ספירת אטומים'],
'Coefficients vs. subscripts':['المعاملات مقابل الأرقام السفلية','מקדמים לעומת מספרים תחתיים'],'Learn exactly what can change during balancing.':['تعلّم بالضبط ما الذي يمكن تغييره أثناء الموازنة.','למדו בדיוק מה ניתן לשנות במהלך האיזון.'],'Reading formulas':['قراءة الصيغ','קריאת נוסחאות'],'Parentheses':['الأقواس','סוגריים'],'Coefficients multiply formulas':['المعاملات تضرب الصيغ','מקדמים מכפילים נוסחאות'],
'Diatomic elements':['العناصر ثنائية الذرة','יסודות דו-אטומיים'],'Recognize the seven common elemental molecules that occur as pairs.':['تعرّف على الجزيئات العنصرية السبعة الشائعة التي توجد على شكل أزواج.','זהו את שבע המולקולות היסודיות הנפוצות שמופיעות כזוגות.'],'When pairing applies':['متى تنطبق الثنائية','מתי הזוגיות חלה'],
'Polyatomic ions':['الأيونات متعددة الذرات','יונים רב-אטומיים'],'Learn when a polyatomic group can be treated as one unit.':['تعلّم متى يمكن التعامل مع المجموعة متعددة الذرات كوحدة واحدة.','למדו מתי אפשר להתייחס לקבוצה רב-אטומית כיחידה אחת.'],'Keeping groups intact':['الحفاظ على المجموعات كاملة','שמירת קבוצות שלמות'],'Checking atoms correctly':['التحقق من الذرات بشكل صحيح','בדיקה נכונה של האטומים'],
'Combustion reactions':['تفاعلات الاحتراق','תגובות בעירה'],'Use a reliable order for balancing hydrocarbons and similar fuels.':['استخدم ترتيبًا موثوقًا لموازنة الهيدروكربونات والوقود المشابه.','השתמשו בסדר אמין לאיזון פחמימנים ודלקים דומים.'],'Balance C first':['وازن C أولًا','אזנו C תחילה'],'Balance H second':['وازن H ثانيًا','אזנו H במקום השני'],'Balance O last':['وازن O أخيرًا','אזנו O בסוף'],
'Common mistakes & worked examples':['الأخطاء الشائعة والأمثلة المحلولة','טעויות נפוצות ודוגמאות פתורות'],'See the errors students make most often, then use complete examples to build a repeatable method.':['اطّلع على الأخطاء الأكثر شيوعًا ثم استخدم أمثلة كاملة لبناء طريقة قابلة للتكرار.','ראו את הטעויות הנפוצות ביותר והשתמשו בדוגמאות מלאות כדי לבנות שיטה עקבית.'],'Never change subscripts':['لا تغيّر الأرقام السفلية','לעולם אל תשנו מספרים תחתונים'],'Check every element':['تحقق من كل عنصر','בדקו כל יסוד'],'Reduce coefficients':['اختصر المعاملات','צמצמו מקדמים'],
'Best way to study:':['أفضل طريقة للدراسة:','הדרך הטובה ביותר ללמוד:'],'CHOOSE YOUR PATH':['اختر مسارك','בחרו את המסלול שלכם'],'Explanation first. Practice second.':['الشرح أولًا. التدريب ثانيًا.','קודם הסבר. אחר כך תרגול.'],'Pick your level and follow the lessons in order. Each path is built around understanding, examples, and practice.':['اختر مستواك واتبع الدروس بالترتيب. كل مسار مبني على الفهم والأمثلة والتدريب.','בחרו את הרמה שלכם ועקבו אחר השיעורים לפי הסדר. כל מסלול מבוסס על הבנה, דוגמאות ותרגול.'],
'BEGINNER · EASY':['مبتدئ · سهل','מתחילים · קל'],'INTERMEDIATE · MEDIUM':['متوسط · متوسط','בינוני · בינוני'],'ADVANCED · HARD':['متقدم · صعب','מתקדם · קשה'],'Build the basics':['ابنِ الأساسيات','בנו את היסודות'],'Handle more structure':['تعامَل مع تراكيب أكثر تعقيدًا','התמודדו עם מבנים מורכבים יותר'],'Challenge yourself':['تحدَّ نفسك','אתגרו את עצמכם'],
'Start Beginner Path':['ابدأ مسار المبتدئين','התחילו במסלול המתחילים'],'Start Intermediate Path':['ابدأ المسار المتوسط','התחילו במסלול הביניים'],'Start Advanced Path':['ابدأ المسار المتقدم','התחילו במסלול המתקדם'],
'What is a chemical equation?':['ما هي المعادلة الكيميائية؟','מהי משוואה כימית؟'],'Reactants, products, reaction arrows, and how to read an equation.':['المتفاعلات والنواتج وأسهم التفاعل وكيفية قراءة المعادلة.','מגיבים, תוצרים, חיצי תגובה וכיצד לקרוא משוואה.'],'Subscripts, parentheses, coefficients, and how atom counts are built.':['الأرقام السفلية والأقواس والمعاملات وكيفية حساب الذرات.','מספרים תחתיים, סוגריים, מקדמים וכיצד סופרים אטומים.'],'Why every element must have the same total atom count on both sides.':['لماذا يجب أن يكون العدد الكلي لذرات كل عنصر متساويًا على الجانبين.','מדוע המספר הכולל של האטומים מכל יסוד חייב להיות זהה בשני הצדדים.'],'A reliable step-by-step method, including a worked example.':['طريقة موثوقة خطوة بخطوة، مع مثال محلول.','שיטה אמינה שלב אחר שלב, כולל דוגמה פתורה.'],'Recognize H₂, N₂, O₂, F₂, Cl₂, Br₂, and I₂ when they are free elements.':['تعرّف على H₂ وN₂ وO₂ وF₂ وCl₂ وBr₂ وI₂ عندما تكون عناصر حرة.','זהו H₂, N₂, O₂, F₂, Cl₂, Br₂ ו-I₂ כאשר הם יסודות חופשיים.'],'Use a final checklist and practise before moving to Intermediate.':['استخدم قائمة التحقق النهائية وتدرّب قبل الانتقال إلى المستوى المتوسط.','השתמשו ברשימת בדיקה סופית ותרגלו לפני המעבר לביניים.'],
'01 · BALANCER':['٠١ · موازنة المعادلات','01 · איזון משוואות'],'03 · BALANCER':['٠٣ · الموازنة','03 · איזון'],'04 · CHECKER':['٠٤ · التحقق','04 · בדיקה'],'02 · PRACTICE & QUIZ':['٠٢ · التدريب والاختبار','02 · תרגול וחידון'],'03 · MULTIPLAYER':['٠٣ · متعدد اللاعبين','03 · משחק רב־משתתפים'],
'Balance equations.':['وازن المعادلات.','אזנו משוואות.'],'Understand why.':['افهم السبب.','הבינו מדוע.'],'Enter a chemical equation and get the balanced result immediately, with optional step-by-step and algebra explanations.':['أدخل معادلة كيميائية واحصل فورًا على النتيجة الموزونة، مع إمكانية عرض شرح خطوة بخطوة وشرح جبري.','הזינו משוואה כימית וקבלו מיד את התוצאה המאוזנת, עם אפשרות להסבר שלב אחר שלב ולהסבר אלגברי.'],'Conservation of atoms':['حفظ الذرات','שימור האטומים'],'The number of each element must be the same on both sides.':['يجب أن يكون عدد ذرات كل عنصر متساويًا على جانبي المعادلة.','מספר האטומים של כל יסוד חייב להיות זהה בשני צדי המשוואה.'],'BALANCE':['موازنة','איזון'],'Balance an equation':['وازن معادلة','אזנו משוואה'],'Try an example':['جرّب مثالًا','נסו דוגמה'],'Balance':['وازن','אזן'],
'Handwriting input':['الإدخال بالكتابة اليدوية','קלט בכתב יד'],'Draw a chemical equation, tap Recognize, check the transcription, then balance it.':['ارسم معادلة كيميائية، واضغط «تعرّف»، وتحقق من النص المُتعرف عليه، ثم وازنها.','ציירו משוואה כימית, לחצו על «זיהוי», בדקו את התמלול ואז אזנו אותה.'],'Draw an equation, then tap Recognize.':['ارسم معادلة، ثم اضغط «تعرّف».','ציירו משוואה ואז לחצו על «זיהוי».'],'Select':['تحديد','בחירה'],'Copy selection':['نسخ التحديد','העתקת הבחירה'],'Paste selection':['لصق التحديد','הדבקת הבחירה'],'Tap Select, then drag around the handwriting.':['اضغط «تحديد»، ثم اسحب حول الكتابة اليدوية.','לחצו על «בחירה» ואז גררו סביב הכתב.'],'Correct the recognized equation before balancing:':['صحّح المعادلة التي تم التعرف عليها قبل الموازنة:','תקנו את המשוואה שזוהתה לפני האיזון:'],'Balance corrected equation':['وازن المعادلة المصححة','אזנו את המשוואה המתוקנת'],'Clear':['مسح','ניקוי'],'Undo':['تراجع','ביטול'],'Redo':['إعادة','ביצוע מחדש'],'Eraser':['ممحاة','מחק'],'Recognize':['تعرّف','זיהוי'],
'Difficulty':['المستوى','רמת קושי'],'Choose a level':['اختر مستوى','בחרו רמה'],'Experience':['نوع التجربة','סוג התרגול'],'Practice or Quiz?':['تدريب أم اختبار؟','תרגול או חידון?'],'Practice — instant feedback':['تدريب — ملاحظات فورية','תרגול — משוב מיידי'],'Quiz — final results':['اختبار — النتيجة النهائية','חידון — תוצאה סופית'],'QUESTION TYPE':['نوع السؤال','סוג השאלה'],'How will you answer?':['كيف ستجيب؟','איך תענו?'],'Multiple choice':['اختيار من متعدد','בחירה מרובה'],'Type the coefficients':['اكتب المعاملات','הקלידו את המקדמים'],'Untimed':['بدون مؤقت','ללא הגבלת זמן'],'Timed · 5 minutes':['مؤقت · 5 دقائق','מתוזמן · 5 דקות'],'Challenge · 60 seconds':['تحدٍ · 60 ثانية','אתגר · 60 שניות'],'Start practice':['ابدأ التدريب','התחל תרגול'],'Start quiz':['ابدأ الاختبار','התחל חידון'],'Practice':['التدريب','תרגול'],'Retry mistakes only':['أعد الأخطاء فقط','תרגלו רק את הטעויות'],'Cancel quiz':['إلغاء الاختبار','ביטול חידון'],
'YOUR PROGRESS':['تقدمك','ההתקדמות שלך'],'Quiz history':['سجل الاختبارات','היסטוריית חידונים'],'Best results and accuracy are stored locally.':['يتم حفظ أفضل النتائج والدقة محليًا.','התוצאות הטובות ביותר והדיוק נשמרים באופן מקומי.'],'Best score':['أفضل نتيجة','שיא'],'Score':['النقاط','ניקוד'],'Correct':['صحيح','נכון'],'Question':['السؤال','שאלה'],'Questions':['الأسئلة','שאלות'],'Accuracy':['الدقة','דיוק'],'Sessions':['الجلسات','סבבים'],
'Check your equation.':['تحقق من معادلتك.','בדקו את המשוואה שלכם.'],'Enter an equation and we’ll check every element, show atom counts, and explain what needs fixing.':['أدخل معادلة وسنتحقق من كل عنصر، ونُظهر عدد الذرات، ونشرح ما يحتاج إلى تصحيح.','הזינו משוואה ונבדוק כל יסוד, נציג ספירת אטומים ונסביר מה צריך לתקן.'],'Your equation':['معادلتك','המשוואה שלכם'],'Check equation':['تحقق من المعادلة','בדקו את המשוואה'],'What gets checked?':['ما الذي يتم التحقق منه؟','מה נבדק؟'],'Same elements on both sides':['العناصر نفسها على الجانبين','אותם יסודות בשני הצדדים'],'Same number of atoms for every element':['العدد نفسه من الذرات لكل عنصر','אותו מספר אטומים מכל יסוד'],'Valid chemical formulas':['الصيغ الكيميائية الصحيحة','נוסחאות כימיות תקינות'],'Simplest whole-number coefficients':['أبسط معاملات بأعداد صحيحة','המקדמים השלמים הקטנים ביותר'],'Need help?':['تحتاج إلى مساعدة؟','זקוקים לעזרה?'],'Open Balancer →':['افتح الموازنة ←','פתחו את המאזן ←'],'Learn how →':['تعلّم الطريقة ←','למדו כיצד ←'],
'✓ Correct element symbols':['✓ رموز العناصر الصحيحة','✓ סמלי יסודות נכונים'],'✓ Correct chemical formulas and subscripts':['✓ الصيغ الكيميائية والأرقام السفلية الصحيحة','✓ נוסחאות כימיות ומספרים תחתיים נכונים'],'✓ Correct diatomic formulas when applicable':['✓ صيغ العناصر الثنائية الصحيحة عند الحاجة','✓ נוסחאות דו־אטומיות נכונות כשנדרש'],'✓ Count atoms on both sides':['✓ عدّ الذرات على الجانبين','✓ ספרו אטומים בשני הצדדים'],'✓ Add coefficients instead of changing formulas':['✓ أضف المعاملات بدلًا من تغيير الصيغ','✓ הוסיפו מקדמים במקום לשנות נוסחאות'],'✓ Recount every element':['✓ أعد عدّ كل عنصر','✓ ספרו מחדש כל יסוד'],'✓ Use the smallest whole-number ratio':['✓ استخدم أصغر نسبة بأعداد صحيحة','✓ השתמשו ביחס השלם הקטן ביותר'],
'Choose how to play':['اختر طريقة اللعب','בחרו איך לשחק'],'Choose how to practice':['اختر طريقة التدريب','בחרו איך לתרגל'],'Solo Practice':['التدريب الفردي','תרגול אישי'],'Multiplayer Challenge':['التحدي متعدد اللاعبين','אתגר רב־משתתפים'],'Practice solo.':['تدرّب بمفردك.','תרגלו לבד.'],'Challenge someone.':['تحدَّ شخصًا آخر.','אתגרו מישהו.'],'Random opponent':['خصم عشوائي','יריב אקראי'],'Invite a specific player':['دعوة لاعب محدد','הזמנת שחקן מסוים'],'Join with challenge code':['الانضمام برمز التحدي','הצטרפות באמצעות קוד אתגר'],'Specific player':['لاعب محدد','שחקן מסוים'],'Same questions':['الأسئلة نفسها','אותן שאלות'],'Live competition':['منافسة مباشرة','תחרות בזמן אמת'],'Live score':['النتيجة المباشرة','ניקוד בזמן אמת'],'Final comparison':['المقارنة النهائية','השוואה סופית'],'How inviting works':['كيفية عمل الدعوة','כיצד פועלת ההזמנה'],'Fastest solvers':['أسرع المتسابقين','הפותרים המהירים ביותר'],'Refresh':['تحديث','רענון'],
'Your profile':['ملفك الشخصي','הפרופיל שלך'],'Please sign in':['يرجى تسجيل الدخول','נא להתחבר'],'Your session has expired or is no longer available.':['انتهت جلستك أو لم تعد متاحة.','פג תוקף ההפעלה שלך או שהיא אינה זמינה יותר.'],'Statistics':['الإحصائيات','סטטיסטיקה'],'Achievements':['الإنجازات','הישגים'],'Completed stages':['المراحل المكتملة','שלבים שהושלמו'],'Recent quizzes':['الاختبارات الأخيرة','חידונים אחרונים'],'Weak areas':['نقاط الضعف','תחומים חלשים'],'Preview achievements & certificate':['معاينة الإنجازات والشهادة','תצוגה מקדימה של הישגים ותעודה'],'Back to my real profile':['العودة إلى ملفي الحقيقي','חזרה לפרופיל האמיתי שלי'],'Preview mode shows the complete design without changing your real progress.':['وضع المعاينة يعرض التصميم الكامل دون تغيير تقدمك الحقيقي.','מצב תצוגה מקדימה מציג את העיצוב המלא בלי לשנות את ההתקדמות האמיתית שלך.'],'Complete Easy, Medium and Hard to unlock your certificate.':['أكمل سهل ومتوسط وصعب لفتح شهادتك.','השלימו קל, בינוני וקשה כדי לפתוח את התעודה.'],'Sign out':['تسجيل الخروج','התנתקות'],'Certificate Preview':['معاينة الشهادة','תצוגת תעודה'],'Close certificate':['إغلاق الشهادة','סגירת התעודה'],'Download / Print Certificate':['تنزيل / طباعة الشهادة','הורדה / הדפסת התעודה'],'Overall score':['النتيجة الإجمالية','ציון כולל'],'Equations solved':['المعادلات المحلولة','משוואות שנפתרו'],'Certificate of Achievement':['شهادة إنجاز','תעודת הישג'],'This certifies that':['تشهد هذه الشهادة بأن','תעודה זו מאשרת כי'],'Date':['التاريخ','תאריך'],'Certificate No.':['رقم الشهادة','מספר התעודה'],'Hard equations':['المعادلات الصعبة','משוואות קשות'],'No completed stages yet.':['لا توجد مراحل مكتملة بعد.','אין עדיין שלבים שהושלמו.'],'No quizzes yet.':['لا توجد اختبارات بعد.','אין עדיין חידונים.'],'Complete more quizzes to identify weak areas.':['أكمل المزيد من الاختبارات لتحديد نقاط الضعف.','השלימו עוד חידונים כדי לזהות תחומים חלשים.'],
'Error':['خطأ','שגיאה'],'Success':['نجاح','הצלחה'],'Loading…':['جارٍ التحميل…','טוען…'],'Show solution':['إظهار الحل','הצג פתרון'],'Hide solution':['إخفاء الحل','הסתר פתרון'],'Explanation':['الشرح','הסבר'],'Hide explanation':['إخفاء الشرح','הסתר הסבר'],'Step-by-step balancing':['الموازنة خطوة بخطوة','איזון שלב אחר שלב'],'Final:':['النتيجة النهائية:','סופי:'],'Copy equation':['نسخ المعادلة','העתקת המשוואה'],'Copy solution':['نسخ الحل','העתקת הפתרון'],'Share':['مشاركة','שיתוף'],'Delete':['حذف','מחיקה'],'Reopen':['إعادة فتح','פתיחה מחדש'],'Clear history':['مسح السجل','ניקוי היסטוריה'],'Equations\' history':['سجل المعادلات','היסטוריית משוואות'],'Balanced result':['النتيجة الموزونة','תוצאה מאוזנת'],'Balance an equation':['وازن معادلة','אזנו משוואה']
};
function current(){const v=localStorage.getItem(KEY);return v==='ar'||v==='he'?v:'en'}
function translated(key,l){const v=T[key];if(!v)return null;return l==='en'?key:(v[l==='ar'?0:1]||key)}
function shouldSkip(node){const p=node.parentElement;return !p||p.closest('script,style,textarea,code,pre,.equation,.chemical-equation,.formula,[data-no-translate]')}
function applyNode(root,l){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];let n;while(walker.nextNode())nodes.push(walker.currentNode);
 for(const node of nodes){if(shouldSkip(node))continue;const raw=node.nodeValue||'',trim=raw.trim();if(!trim)continue;const v=translated(trim,l);if(v&&v!==trim){const lead=raw.match(/^\s*/)?.[0]||'',trail=raw.match(/\s*$/)?.[0]||'';node.nodeValue=lead+v+trail}}
 const els=root.querySelectorAll?root.querySelectorAll('input,button,a,[aria-label],[title]'):[];
 els.forEach(el=>{if(el.closest('script,style,.equation,.chemical-equation,.formula,[data-no-translate]'))return;for(const attr of ['placeholder','aria-label','title']){const v=el.getAttribute(attr);const tr=v&&translated(v.trim(),l);if(tr&&tr!==v.trim())el.setAttribute(attr,tr)}})
}
function installStyle(){if(document.getElementById('chemistry-language-rtl-style'))return;const s=document.createElement('style');s.id='chemistry-language-rtl-style';s.textContent=`
html[dir="rtl"] body{direction:rtl;text-align:right}
html[dir="rtl"] .topbar,html[dir="rtl"] main,html[dir="rtl"] footer{direction:rtl}
html[dir="rtl"] .main-nav{direction:rtl;flex-wrap:wrap}
html[dir="rtl"] .hero,html[dir="rtl"] .hero>div,html[dir="rtl"] .hero-card,html[dir="rtl"] .section-head,html[dir="rtl"] .card,html[dir="rtl"] .lesson,html[dir="rtl"] .course-map,html[dir="rtl"] .lesson-grid,html[dir="rtl"] .grid-2,html[dir="rtl"] .dashboard-grid,html[dir="rtl"] .profile-page,html[dir="rtl"] .handwriting,html[dir="rtl"] .tips,html[dir="rtl"] .next-card{direction:rtl;text-align:right}
html[dir="rtl"] h1,html[dir="rtl"] h2,html[dir="rtl"] h3,html[dir="rtl"] p,html[dir="rtl"] label,html[dir="rtl"] .eyebrow,html[dir="rtl"] .section-head>div{text-align:right}
html[dir="rtl"] .section-head{align-items:flex-start}
html[dir="rtl"] .input-row,html[dir="rtl"] .hand-head,html[dir="rtl"] .hand-actions,html[dir="rtl"] .quiz-actions,html[dir="rtl"] .help-actions{direction:rtl}
html[dir="rtl"] button,html[dir="rtl"] .primary,html[dir="rtl"] .secondary{direction:rtl;text-align:center}
html[dir="rtl"] input,html[dir="rtl"] textarea,html[dir="rtl"] select{direction:rtl;text-align:right}
html[dir="rtl"] .chips{direction:rtl}
html[dir="rtl"] table{direction:rtl}
html[dir="rtl"] .certificate,html[dir="rtl"] .certificate *{direction:rtl}
html[dir="rtl"] .equation,html[dir="rtl"] .equation *,html[dir="rtl"] .chemical-equation,html[dir="rtl"] .chemical-equation *,html[dir="rtl"] .formula,html[dir="rtl"] .history-equation,html[dir="rtl"] .history-solution,html[dir="rtl"] .history-label-solution{direction:ltr!important;text-align:center!important;unicode-bidi:isolate}
html[dir="rtl"] canvas{direction:ltr!important}
html[dir="rtl"] .brand{direction:ltr;text-align:left}
#site-language-selector{position:fixed;top:10px;inset-inline-end:10px;z-index:2147483647;padding:7px 10px;border:1px solid rgba(0,0,0,.18);border-radius:9px;background:#fff;font:inherit;min-width:112px;box-shadow:0 2px 10px rgba(0,0,0,.12)}
@media(max-width:700px){html[dir="rtl"] .topbar{align-items:stretch}html[dir="rtl"] .main-nav{justify-content:flex-start}html[dir="rtl"] .input-row{flex-direction:column;align-items:stretch}html[dir="rtl"] .input-row>*{width:100%;box-sizing:border-box}}
`;document.head.appendChild(s)}
function setDirection(l){document.documentElement.lang=l;document.documentElement.dir=RTL.has(l)?'rtl':'ltr';document.body.classList.toggle('rtl-language',RTL.has(l));installStyle()}
function apply(l){setDirection(l);applyNode(document.body,l);const s=document.getElementById('site-language-selector');if(s)s.value=l}
function addSelector(){let s=document.getElementById('site-language-selector');if(!s){s=document.createElement('select');s.id='site-language-selector';s.setAttribute('aria-label','Language');s.innerHTML='<option value="en">English</option><option value="ar">العربية</option><option value="he">עברית</option>';s.addEventListener('change',()=>{localStorage.setItem(KEY,s.value);location.reload()});document.body.appendChild(s)}s.value=current()}
function translateSite(){apply(current())}
window.translateSite=translateSite;
function init(){addSelector();apply(current());}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
// Watch only inserted DOM nodes. Text-node changes made by this script cannot retrigger it.
const observer=new MutationObserver(ms=>{const l=current();for(const m of ms)for(const node of m.addedNodes){if(node.nodeType===1)applyNode(node,l)}});
if(document.body)observer.observe(document.body,{childList:true,subtree:true});else document.addEventListener('DOMContentLoaded',()=>observer.observe(document.body,{childList:true,subtree:true}),{once:true});
})();