(()=>{
'use strict';
const KEY='chemistryLanguage';
const LANGS={en:{label:'English',dir:'ltr'},ar:{label:'العربية',dir:'rtl'},he:{label:'עברית',dir:'rtl'}};
const T={
'Learn':{ar:'تعلّم',he:'למידה'},'Quiz':{ar:'اختبار',he:'חידון'},'Challenges':{ar:'التحديات',he:'אתגרים'},'Balancer':{ar:'موازنة المعادلات',he:'איזון משוואות'},'Checker':{ar:'التحقق',he:'בדיקה'},'Account':{ar:'الحساب',he:'חשבון'},
'3 · BALANCER':{ar:'3 · الموازنة',he:'3 · איזון משוואות'},'Balance equations.':{ar:'وازن المعادلات.',he:'אזנו משוואות.'},'Understand why.':{ar:'افهم السبب.',he:'הבינו מדוע.'},'Enter a chemical equation and get the balanced result immediately, with optional step-by-step and algebra explanations.':{ar:'أدخل معادلة كيميائية واحصل فورًا على المعادلة الموزونة، مع إمكانية عرض شرح خطوة بخطوة وشرح جبري.',he:'הזינו משוואה כימית וקבלו מיד את התוצאה המאוזנת, עם אפשרות להסבר שלב אחר שלב ולהסבר אלגברי.'},
'Conservation of atoms':{ar:'حفظ الذرات',he:'שימור האטומים'},'The number of each element must be the same on both sides.':{ar:'يجب أن يكون عدد ذرات كل عنصر متساويًا على جانبي المعادلة.',he:'מספר האטומים של כל יסוד חייב להיות זהה בשני צדי המשוואה.'},'BALANCE':{ar:'موازنة',he:'איזון'},'Balance an equation':{ar:'وازن معادلة',he:'אזנו משוואה'},'Try an example':{ar:'جرّب مثالًا',he:'נסו דוגמה'},'Balance':{ar:'وازن',he:'אזן'},
'Handwriting input':{ar:'الإدخال بالكتابة اليدوية',he:'קלט בכתב יד'},'Recognizes subscripts, coefficients and reaction arrows. You can correct the recognized equation before balancing.':{ar:'يتعرّف على الأرقام السفلية والمعاملات وأسهم التفاعل. يمكنك تصحيح المعادلة التي تم التعرف عليها قبل موازنتها.',he:'מזהה מספרים תחתיים, מקדמים וחיצי תגובה. ניתן לתקן את המשוואה שזוהתה לפני האיזון.'},'Clear':{ar:'مسح',he:'ניקוי'},'Undo':{ar:'تراجع',he:'ביטול'},'Redo':{ar:'إعادة',he:'ביצוע מחדש'},'Eraser':{ar:'ممحاة',he:'מחק'},'Recognize':{ar:'تعرّف',he:'זיהוי'},'Draw an equation, then tap Recognize.':{ar:'ارسم معادلة، ثم اضغط على «تعرّف».',he:'ציירו משוואה ולאחר מכן לחצו על «זיהוי».'},
'Choose a level':{ar:'اختر المستوى',he:'בחרו רמה'},'Easy':{ar:'سهل',he:'קל'},'Medium':{ar:'متوسط',he:'בינוני'},'Hard':{ar:'صعب',he:'קשה'},'Basics and simple equations':{ar:'الأساسيات والمعادلات البسيطة',he:'יסודות ומשוואות פשוטות'},'Groups, parentheses and more steps':{ar:'المجموعات والأقواس والمزيد من الخطوات',he:'קבוצות, סוגריים ושלבים נוספים'},'Combustion and complex reactions':{ar:'الاحتراق والتفاعلات المعقدة',he:'בעירה ותגובות מורכבות'},'How do you want to practice?':{ar:'كيف تريد أن تتدرّب؟',he:'איך תרצו לתרגל?'},'Choose how to play':{ar:'اختر طريقة اللعب',he:'בחרו איך לשחק'},'Choose how to practice':{ar:'اختر طريقة التدريب',he:'בחרו איך לתרגל'},'Untimed':{ar:'بدون مؤقت',he:'ללא הגבלת זמן'},'Timed · 5 minutes':{ar:'مؤقت · 5 دقائق',he:'מתוזמן · 5 דקות'},'Challenge · 60 seconds':{ar:'تحدٍّ · 60 ثانية',he:'אתגר · 60 שניות'},'Start new quiz':{ar:'ابدأ اختبارًا جديدًا',he:'התחילו חידון חדש'},
'Solo Practice':{ar:'التدريب الفردي',he:'תרגול אישי'},'Multiplayer Challenge':{ar:'تحدي متعدد اللاعبين',he:'אתגר רב־משתתפים'},'Practice solo.':{ar:'تدرّب بمفردك.',he:'תרגלו לבד.'},'Challenge someone.':{ar:'تحدَّ شخصًا آخر.',he:'אתגרו מישהו.'},'Random opponent':{ar:'خصم عشوائي',he:'יריב אקראי'},'Invite a specific player':{ar:'دعوة لاعب محدد',he:'הזמנת שחקן מסוים'},'Join with challenge code':{ar:'الانضمام برمز التحدي',he:'הצטרפות באמצעות קוד אתגר'},'Specific player':{ar:'لاعب محدد',he:'שחקן מסוים'},'Same questions':{ar:'الأسئلة نفسها',he:'אותן שאלות'},'Live competition':{ar:'منافسة مباشرة',he:'תחרות בזמן אמת'},'Live score':{ar:'النتيجة المباشرة',he:'ניקוד בזמן אמת'},'Final comparison':{ar:'المقارنة النهائية',he:'השוואה סופية'},'How inviting works':{ar:'كيفية عمل الدعوة',he:'כיצד פועלת ההזמנה'},'Fastest solvers':{ar:'أسرع المتسابقين',he:'הפותרים המהירים ביותר'},'Refresh':{ar:'تحديث',he:'רענון'},
'Solo Practice and Multiplayer Challenge are separate experiences. In a challenge, both players get the same questions and race against the clock.':{ar:'التدريب الفردي والتحدي متعدد اللاعبين تجربتان منفصلتان. في التحدي، يحصل كلا اللاعبين على الأسئلة نفسها ويتنافسان ضد الساعة.',he:'תרגול אישי ואתגר רב־משתתפים הם שתי חוויות נפרדות. באתגר, שני השחקנים מקבלים את אותן שאלות ומתחרים נגד השעון.'},'Match with an available player.':{ar:'طابقك مع لاعب متاح.',he:'התאימו אתכם לשחקן זמין.'},'Create a private room and send the player your challenge code or link.':{ar:'أنشئ غرفة خاصة وأرسل للاعب رمز التحدي أو الرابط.',he:'צרו חדר פרטי ושלחו לשחקן את קוד האתגר או הקישור.'},'Both players receive the identical question set.':{ar:'يحصل كلا اللاعبين على مجموعة الأسئلة نفسها.',he:'שני השחקנים מקבלים בדיוק את אותה קבוצת שאלות.'},'Timer and progress update while you solve.':{ar:'يتم تحديث المؤقت والتقدم أثناء الحل.',he:'הטיימר וההתקדמות מתעדכנים בזמן הפתרון.'},'Track your progress during the match.':{ar:'تابع تقدمك أثناء المباراة.',he:'עקבו אחר ההתקדמות שלכם במהלך המשחק.'},'See both scores and who won after a real challenge.':{ar:'شاهد نتيجتي اللاعبين ومن فاز بعد انتهاء التحدي.',he:'ראו את שתי התוצאות ומי ניצח לאחר انتهاء האתגר.'},'Choose “Invite a specific player”, create a private challenge, then send the generated challenge code or share link to that player. They can join from this page.':{ar:'اختر «دعوة لاعب محدد»، وأنشئ تحديًا خاصًا، ثم أرسل رمز التحدي الذي تم إنشاؤه أو رابط المشاركة إلى اللاعب. يمكنه الانضمام من هذه الصفحة.',he:'בחרו «הזמנת שחקן מסוים», צרו אתגר פרטי ולאחר מכן שלחו לשחקן את קוד האתגר שנוצר או קישור השיתוף. הוא יוכל להצטרף מדף זה.'},'Leaderboard will appear when the multiplayer server is connected.':{ar:'ستظهر لوحة المتصدرين عند الاتصال بخادم اللعب متعدد اللاعبين.',he:'טבלת המובילים תופיע כאשר שרת המשחק הרב־משתתפים יהיה מחובר.'},
'Check your equation.':{ar:'تحقق من معادلتك.',he:'בדקו את המשוואה שלכם.'},"Enter your balanced equation and we'll check every element and coefficient.":{ar:'أدخل معادلتك الموزونة وسنتحقق من كل عنصر وكل معامل.',he:'הזינו את המשוואה המאוזנת שלכם ונבדוק כל יסוד וכל מקדם.'},'Your equation':{ar:'معادلتك',he:'המשוואה שלכם'},'Check equation':{ar:'تحقق من المعادلة',he:'בדקו את המשוואה'},'What gets checked?':{ar:'ما الذي يتم التحقق منه؟',he:'מה נבדק?'},'Same elements on both sides':{ar:'العناصر نفسها على الجانبين',he:'אותם יסודות בשני הצדדים'},'Same number of atoms for every element':{ar:'العدد نفسه من الذرات لكل عنصر',he:'אותו מספר אטומים מכל יסוד'},'Valid chemical formulas':{ar:'الصيغ الكيميائية الصحيحة',he:'נוסחאות כימיות תקינות'},'Simplest whole-number coefficients':{ar:'أبسط معاملات بأعداد صحيحة',he:'המקדמים השלמים הקטנים ביותר'},'Need help?':{ar:'تحتاج إلى مساعدة؟',he:'זקוקים לעזרה?'},'Learn how':{ar:'تعلّم الطريقة',he:'למדו כיצד'},'Settings':{ar:'الإعدادات',he:'הגדרות'},'Privacy & Security':{ar:'الخصوصية والأمان',he:'פרטיות ואבטחה'},'Change password':{ar:'تغيير كلمة المرور',he:'שינוי סיסמה'},'Sign in':{ar:'تسجيل الدخول',he:'התחברות'},'Sign out':{ar:'تسجيل الخروج',he:'התנתקות'},'Remember me':{ar:'تذكرني',he:'זכור אותי'}
};
function keyOf(el){return el.dataset.i18nOriginal||el.textContent.trim()}
function tr(text,l){const k=text.trim();return l==='en'?k:(T[k]?.[l]||k)}
function remember(){document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0&&!el.dataset.i18nOriginal&&el.textContent.trim()&&!el.closest('input,textarea,canvas,code,pre,.equation,.chemical-equation,.formula,[data-equation],.math'))el.dataset.i18nOriginal=el.textContent.trim()})}
function apply(l){if(!LANGS[l])l='en';remember();document.documentElement.lang=l;document.documentElement.dir=LANGS[l].dir;document.body.dir=LANGS[l].dir;document.body.classList.toggle('rtl-language',l!=='en');document.body.classList.toggle('ltr-language',l==='en');document.querySelectorAll('[data-i18n-original]').forEach(el=>{el.textContent=tr(el.dataset.i18nOriginal,l)});document.querySelectorAll('.equation,.chemical-equation,.formula,[data-equation],.math,code,pre').forEach(el=>{el.dir='ltr';el.style.direction='ltr'});localStorage.setItem(KEY,l);ensureSelector(l)}
function ensureSelector(l){let s=document.getElementById('site-language-selector');if(!s){s=document.createElement('select');s.id='site-language-selector';s.setAttribute('aria-label','Language');s.innerHTML='<option value="en">English</option><option value="ar">العربية</option><option value="he">עברית</option>';s.addEventListener('change',()=>apply(s.value));document.body.appendChild(s)}s.value=l;s.dir='ltr';s.style.cssText='position:fixed;top:12px;right:12px;z-index:2147483647;padding:7px 10px;border-radius:8px;background:#fff;color:#111;border:1px solid #bbb;direction:ltr'}
function init(){apply(localStorage.getItem(KEY)||'en');new MutationObserver(()=>{const l=localStorage.getItem(KEY)||'en';if(document.getElementById('site-language-selector'))apply(l)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();