(()=>{'use strict';
const PAGES=[['Learn','learn.html'],['Quiz','personal-quiz.html'],['Challenges','challenges.html'],['Balancer','index.html'],['Checker','checker.html'],['Beginner Lessons','beginner-lessons.html'],['Intermediate Lessons','intermediate-lessons.html'],['Advanced Lessons','advanced-lessons.html'],['Profile','profile.html']];
const clean=s=>String(s??'').replace(/[\u200b-\u200d\ufeff]/g,'').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const terms=q=>clean(q).toLowerCase().split(/\s+/).filter(Boolean);
const pageName=(doc,p)=>clean(doc.title||'').replace(/\s*[—|-].*$/,'')||PAGES.find(x=>x[1]===p)?.[0]||p;
const makeIndex=(doc,p)=>{const root=doc.querySelector('main')||doc.body,heads=[...root.querySelectorAll('h1,h2,h3,h4')],out=[];if(!heads.length){const text=clean(root.innerText||root.textContent);if(text)out.push({page:p,name:pageName(doc,p),section:pageName(doc,p),text,anchor:'',key:text.slice(0,180)});return out}heads.forEach(h=>{const section=h.closest('section,article,.card')||h.parentElement||root,text=clean(section.innerText||section.textContent);if(text)out.push({page:p,name:pageName(doc,p),section:clean(h.innerText||h.textContent)||pageName(doc,p),text,anchor:h.id||section.id||'',key:text.slice(0,180)})});return out};
const currentPage=()=>location.pathname.split('/').pop()||'index.html';
const snippet=(text,qs)=>{const t=clean(text),l=t.toLowerCase(),phrase=qs.join(' ');let at=l.indexOf(phrase);if(at<0){at=Infinity;qs.forEach(q=>{const i=l.indexOf(q);if(i>=0)at=Math.min(at,i)})}if(at===Infinity)return t.slice(0,240);const a=Math.max(0,at-110),z=Math.min(t.length,at+150);return (a?'…':'')+t.slice(a,z)+(z<t.length?'…':'')};
const highlight=(text,qs)=>{let out=esc(text);const ss=[...qs].sort((a,b)=>b.length-a.length).map(q=>q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));return ss.length?out.replace(new RegExp('('+ss.join('|')+')','ig'),'<strong>$1</strong>'):out};
function mark(el){if(!el)return;const target=el.closest('section,article,.card')||el;target.scrollIntoView({behavior:'smooth',block:'center'});target.classList.add('site-search-target');setTimeout(()=>target.classList.remove('site-search-target'),2800)}
function findExact(q){const qs=terms(q),phrase=qs.join(' '),walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];let n;while(n=walker.nextNode()){const el=n.parentElement;if(!el||el.closest('#siteSearchBar'))continue;const t=clean(n.nodeValue),l=t.toLowerCase();if(l.includes(phrase)||qs.some(x=>l.includes(x)))nodes.push(el)}if(!nodes.length)return false;const exact=nodes.find(el=>clean(el.textContent).toLowerCase().includes(phrase))||nodes[0];mark(exact);return true}
function consume(){try{const x=JSON.parse(sessionStorage.getItem('chemistrySearchTarget')||'null');sessionStorage.removeItem('chemistrySearchTarget');if(!x||x.page!==currentPage())return;setTimeout(()=>{if(x.anchor){const el=document.getElementById(x.anchor);if(el){mark(el);return}}findExact(x.query)},350)}catch{}}
function init(){if(!document.querySelector('.topbar'))return;document.getElementById('siteSearchBar')?.remove();const bar=document.createElement('div');bar.id='siteSearchBar';bar.innerHTML='<div class="site-search-inner"><span class="site-search-icon">⌕</span><input id="siteSearchInput" type="search" autocomplete="off" placeholder="Search the whole site…" aria-label="Search the whole site"><button id="siteSearchClear" type="button" aria-label="Clear">×</button><div id="siteSearchResults"></div></div>';document.querySelector('.topbar').insertAdjacentElement('afterend',bar);
if(!document.getElementById('searchFixStyle')){const css=document.createElement('style');css.id='searchFixStyle';css.textContent='#siteSearchBar{position:relative;z-index:9000;width:100%;padding:10px 16px 12px;background:var(--bg)}.site-search-inner{position:relative;width:min(1100px,100%);margin:auto}.site-search-inner input{width:100%;height:46px;box-sizing:border-box;padding:0 50px 0 42px;border:1px solid var(--line);border-radius:13px;background:var(--surface);color:var(--text);font:inherit;outline:0}.site-search-icon{position:absolute;left:14px;top:50%;transform:translateY(-50%);font-size:21px;color:var(--muted);pointer-events:none}.site-search-inner input:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(49,88,214,.12)}#siteSearchClear{position:absolute;right:7px;top:7px;width:32px;height:32px;border:0;background:transparent;color:var(--muted);font-size:22px;cursor:pointer}#siteSearchResults{display:none;position:absolute;left:0;right:0;top:53px;max-height:65vh;overflow:auto;background:var(--surface);border:1px solid var(--line);border-radius:13px;box-shadow:0 14px 35px rgba(15,23,42,.16)}#siteSearchResults.open{display:block}.site-result,.site-quick-item{display:block;padding:12px 15px;color:var(--text);text-decoration:none;border-bottom:1px solid var(--line);cursor:pointer}.site-result:hover,.site-result.active,.site-quick-item:hover{background:rgba(49,88,214,.08)}.site-result b{display:block;font-size:14px}.site-section{display:block;color:var(--accent);font-size:12px;font-weight:800;margin-top:4px}.site-match{display:block;font-size:12px;line-height:1.45;margin-top:4px}.site-match strong{font-weight:900;background:rgba(49,88,214,.18);border-radius:3px;padding:0 2px}.site-go{display:block;color:var(--accent);font-size:11px;margin-top:5px;font-weight:800}.site-quick{display:block;padding:10px 15px 6px;color:var(--muted);font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.site-search-target{outline:3px solid rgba(49,88,214,.5);outline-offset:6px;border-radius:8px;transition:outline-color .2s}@media(max-width:760px){#siteSearchBar{padding:8px 10px 10px}.site-search-inner input{height:44px;font-size:14px}.site-search-inner input{padding-left:40px}#siteSearchResults{top:51px;max-height:70vh}.site-result,.site-quick-item{padding:14px 13px}.site-match{font-size:13px}.site-go{font-size:12px}}';document.head.appendChild(css)}
const input=document.getElementById('siteSearchInput'),res=document.getElementById('siteSearchResults'),clear=document.getElementById('siteSearchClear');let data=makeIndex(document,currentPage()),active=-1;
const quick=[['Balance an equation','index.html'],['Daily Challenge','learn.html#dailyChallenge'],['Take a Quiz','personal-quiz.html'],['Start Learning','learn.html']];
function render(q){q=clean(q);active=-1;if(!q){res.innerHTML='<div class="site-quick">Quick access</div>'+quick.map(([n,p])=>'<a class="site-quick-item" href="'+esc(p)+'">'+esc(n)+'</a>').join('');res.classList.add('open');return}const qs=terms(q),lower=q.toLowerCase(),hits=data.map(x=>{let score=0;const sec=x.section.toLowerCase(),name=x.name.toLowerCase(),text=x.text.toLowerCase();qs.forEach(t=>{if(sec.includes(t))score+=45;if(name.includes(t))score+=25;if(text.includes(t))score+=4});if(text.includes(lower))score+=35;if(sec===lower)score+=60;return {...x,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,10);res.innerHTML=hits.length?hits.map((x,i)=>{const href=x.page+(x.anchor?'#'+encodeURIComponent(x.anchor):'');return '<a class="site-result" data-page="'+esc(x.page)+'" data-anchor="'+esc(x.anchor)+'" data-query="'+esc(q)+'" href="'+esc(href)+'" aria-label="'+esc(x.name+' — '+x.section)+'"><b>'+esc(x.name)+'</b><span class="site-section">Matching section: '+esc(x.section)+'</span><span class="site-match">'+highlight(snippet(x.text,qs),qs)+'</span><span class="site-go">Go to this section</span></a>'}).join(''):'<div class="site-result"><b>No matching results</b><span class="site-match">Try another word or phrase.</span></div>';res.classList.add('open');const links=[...res.querySelectorAll('a.site-result')];if(links.length){active=0;links[0].classList.add('active')}}
input.addEventListener('focus',()=>render(input.value));input.addEventListener('input',()=>render(input.value));clear.addEventListener('click',()=>{input.value='';render('');input.focus()});
input.addEventListener('keydown',e=>{const links=[...res.querySelectorAll('a.site-result')];if(e.key==='Escape'){res.classList.remove('open');return}if((e.key==='ArrowDown'||e.key==='ArrowUp')&&links.length){e.preventDefault();active=(active+(e.key==='ArrowDown'?1:-1)+links.length)%links.length;links.forEach((a,i)=>a.classList.toggle('active',i===active));links[active].scrollIntoView({block:'nearest'})}else if(e.key==='Enter'&&links.length){e.preventDefault();links[Math.max(0,active)].click()}});
res.addEventListener('click',e=>{const a=e.target.closest('a.site-result');if(!a)return;const p=a.dataset.page,q=a.dataset.query,anchor=a.dataset.anchor;if(currentPage()!==p){sessionStorage.setItem('chemistrySearchTarget',JSON.stringify({page:p,anchor,query:q}));return}e.preventDefault();if(anchor){const el=document.getElementById(anchor);if(el)mark(el);else findExact(q)}else findExact(q);res.classList.remove('open')});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus();input.select();render(input.value)}});document.addEventListener('click',e=>{if(!bar.contains(e.target))res.classList.remove('open')});
function fetchPage(p){const base=location.href.substring(0,location.href.lastIndexOf('/')+1),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),5000);return fetch(base+p,{cache:'no-store',signal:ctl.signal}).then(r=>r.ok?r.text():null).then(html=>{if(!html)return;const d=new DOMParser().parseFromString(html,'text/html');data.push(...makeIndex(d,p));if(input.value)render(input.value)}).catch(()=>{}).finally(()=>clearTimeout(timer))}
render('');PAGES.filter(x=>x[1]!==currentPage()).forEach(x=>fetchPage(x[1]));consume()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();