(()=>{'use strict';
const PAGES=[
 ['index.html','Learn','learning, chemistry, balancing, lessons'],
 ['personal-quiz.html','Quiz','quiz, practice, questions, score'],
 ['challenges.html','Challenges','challenge, multiplayer, opponent, leaderboard'],
 ['balancer.html','Balancer','balance, equation, coefficients, chemistry'],
 ['checker.html','Checker','check, equation, answer, validation'],
 ['beginner-lessons.html','Beginner Lessons','beginner, basics, conservation, coefficients'],
 ['intermediate-lessons.html','Intermediate Lessons','intermediate, polyatomic, parentheses, fractions'],
 ['advanced-lessons.html','Advanced Lessons','advanced, combustion, redox, ionic'],
 ['profile.html','Profile','account, progress, achievements, streak, results'],
 ['admin.html','Admin','admin, tools']
];
const tr=(en,ar,he)=>{const l=localStorage.getItem('chemistryLanguage')||'en';return l==='ar'?ar:l==='he'?he:en};
const esc=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const norm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');
const install=()=>{if(document.getElementById('siteSearch'))return;const top=document.querySelector('.topbar');if(!top)return;
 const wrap=document.createElement('div');wrap.id='siteSearch';wrap.innerHTML=`<div class="site-search-inner"><label class="site-search-label" for="siteSearchInput">🔎 <span>${tr('Search the site','ابحث في الموقع','חיפוש באתר')}</span></label><div class="site-search-box"><input id="siteSearchInput" type="search" autocomplete="off" placeholder="${esc(tr('Search lessons, equations, quizzes…','ابحث عن الدروس والمعادلات والاختبارات…','חפשו שיעורים, משוואות וחידונים…'))}" aria-label="${esc(tr('Search the site','ابحث في الموقع','חיפוש באתר'))}"><button id="siteSearchClear" type="button" aria-label="Clear search" hidden>×</button></div><div id="siteSearchResults" class="site-search-results" hidden></div></div>`;
 top.insertAdjacentElement('afterend',wrap);
 const input=wrap.querySelector('#siteSearchInput'),clear=wrap.querySelector('#siteSearchClear'),results=wrap.querySelector('#siteSearchResults');
 const candidates=[...PAGES];document.querySelectorAll('a[href]').forEach(a=>{const href=a.getAttribute('href');if(!href||/^https?:|^mailto:|^javascript:|^#/.test(href))return;const file=href.split('?')[0].split('#')[0].split('/').pop();if(file&&file.endsWith('.html')&&!candidates.some(p=>p[0]===file))candidates.push([file,a.textContent.trim()||file,''])});
 const cache=new Map();
 const getPage=async([file,title,keywords])=>{if(cache.has(file))return cache.get(file);if(file===(location.pathname.split('/').pop()||'index.html')){const v={file,title,keywords,text:document.body.innerText};cache.set(file,v);return v}try{const r=await fetch(file,{cache:'no-store'});if(!r.ok)throw 0;const html=await r.text(),doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,style,noscript').forEach(e=>e.remove());const v={file,title:doc.title.replace(/\s*[—|-].*$/,''),keywords,text:doc.body?.innerText||''};cache.set(file,v);return v}catch{return null}};
 const render=items=>{if(!items.length){results.innerHTML=`<div class="site-search-empty">${tr('No matching pages found.','لم يتم العثور على صفحات مطابقة.','לא נמצאו דפים תואמים.')}</div>`;results.hidden=false;return}results.innerHTML=items.slice(0,8).map(x=>`<a class="site-search-result" href="${esc(x.file)}"><b>${esc(x.title)}</b><span>${esc(x.snippet)}</span></a>`).join('');results.hidden=false};
 let token=0;const search=async()=>{const q=input.value.trim();clear.hidden=!q;if(!q){results.hidden=true;return}const t=++token;results.innerHTML=`<div class="site-search-empty">${tr('Searching…','جارٍ البحث…','מחפש…')}</div>`;results.hidden=false;const nq=norm(q),data=await Promise.all(candidates.map(getPage));if(t!==token)return;const hits=data.filter(Boolean).map(p=>{const hay=norm(`${p.title} ${p.keywords} ${p.text}`);const idx=hay.indexOf(nq);if(idx<0)return null;const raw=p.text.replace(/\s+/g,' ').trim(),ri=Math.max(0,raw.toLowerCase().indexOf(q.toLowerCase()));return {file:p.file,title:p.title,snippet:raw.slice(Math.max(0,ri-70),Math.min(raw.length,ri+170))||p.keywords}}).filter(Boolean);render(hits)};
 input.addEventListener('input',search);input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';clear.hidden=true;results.hidden=true}});clear.addEventListener('click',()=>{input.value='';clear.hidden=true;results.hidden=true;input.focus()});document.addEventListener('click',e=>{if(!wrap.contains(e.target))results.hidden=true});
};
const style=()=>{if(document.getElementById('siteSearchStyle'))return;const s=document.createElement('style');s.id='siteSearchStyle';s.textContent=`#siteSearch{position:relative;z-index:20;padding:0 20px}.site-search-inner{max-width:1180px;margin:0 auto;padding:10px 0 2px}.site-search-label{display:flex;align-items:center;gap:6px;font-size:12px;font-weight:800;color:var(--muted);margin-bottom:5px}.site-search-box{position:relative}.site-search-box input{width:100%;box-sizing:border-box;height:42px;padding:9px 38px 9px 13px;border:1px solid var(--line);border-radius:12px;background:var(--surface);color:var(--text);font:inherit;outline:none}.site-search-box input:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(49,88,214,.12)}.site-search-box button{position:absolute;right:7px;top:7px;width:28px;height:28px;border:0;background:transparent;color:var(--muted);font-size:22px;line-height:1;cursor:pointer}.site-search-results{margin-top:6px;border:1px solid var(--line);border-radius:12px;background:var(--surface);box-shadow:0 14px 32px rgba(31,48,82,.12);overflow:hidden}.site-search-result{display:block;padding:11px 13px;text-decoration:none;color:inherit;border-bottom:1px solid var(--line)}.site-search-result:last-child{border-bottom:0}.site-search-result b{display:block;font-size:14px}.site-search-result span{display:block;margin-top:3px;color:var(--muted);font-size:12px;line-height:1.4}.site-search-result:hover{background:var(--surface-2,#f7f9fc)}.site-search-empty{padding:13px;color:var(--muted);font-size:13px}@media(max-width:760px){#siteSearch{padding:0 12px}.site-search-inner{padding-top:7px}.site-search-box input{height:40px}}`;document.head.appendChild(s)};
const init=()=>{style();install()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
