(()=>{
const KEY='chemistryStudentProduct';
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
let state=get(); state.solved=Number(state.solved)||0; state.correct=Number(state.correct)||0; state.xp=Number(state.xp)||0; state.streak=Number(state.streak)||0; state.lastDay=state.lastDay||''; state.level=Number(state.level)||1; state.badges=Array.isArray(state.badges)?state.badges:[]; state.daily=state.daily||''; state.dailyDate=state.dailyDate||''; state.exam=state.exam||null; save(state);
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const addStyles=()=>{if(document.getElementById('student-product-css'))return;const l=document.createElement('link');l.id='student-product-css';l.rel='stylesheet';l.href='student-product.css?v=20260830-1';document.head.appendChild(l)};
const mount=(el,html)=>{if(!el)return null;const d=document.createElement('div');d.className='student-product';d.innerHTML=html;el.insertAdjacentElement('afterend',d);return d};
const dailyEq=()=>{const pool=['H2 + O2 -> H2O','Fe + O2 -> Fe2O3','C3H8 + O2 -> CO2 + H2O','Na + Cl2 -> NaCl','Ca(OH)2 + HCl -> CaCl2 + H2O','Al + O2 -> Al2O3','KClO3 -> KCl + O2'];const n=(Number(today().replaceAll('-',''))%pool.length);return pool[n]};
const balanceExpected={
'H2 + O2 -> H2O':'2H2 + O2 -> 2H2O','Fe + O2 -> Fe2O3':'4Fe + 3O2 -> 2Fe2O3','C3H8 + O2 -> CO2 + H2O':'C3H8 + 5O2 -> 3CO2 + 4H2O','Na + Cl2 -> NaCl':'2Na + Cl2 -> 2NaCl','Ca(OH)2 + HCl -> CaCl2 + H2O':'Ca(OH)2 + 2HCl -> CaCl2 + 2H2O','Al + O2 -> Al2O3':'4Al + 3O2 -> 2Al2O3','KClO3 -> KCl + O2':'2KClO3 -> 2KCl + 3O2'};
const normalize=x=>String(x||'').replace(/[→=]/g,'->').replace(/\s+/g,'').toUpperCase();
function reward(correct,kind='practice'){state.solved++;if(correct)state.correct++;if(correct)state.xp+=kind==='exam'?50:25;if(correct&&state.lastDay!==today()){const y=new Date();y.setDate(y.getDate()-1);const prev=y.toISOString().slice(0,10);state.streak=state.lastDay===prev?state.streak+1:1;state.lastDay=today()}if(state.solved>=1&&!state.badges.includes('first'))state.badges.push('first');if(state.correct>=10&&!state.badges.includes('counter'))state.badges.push('counter');if(state.streak>=3&&!state.badges.includes('streak'))state.badges.push('streak');if(state.correct>=25&&!state.badges.includes('expert'))state.badges.push('expert');state.level=Math.min(5,1+Math.floor(state.correct/5));save(state)}
function progressHTML(){const acc=state.solved?Math.round(state.correct/state.solved*100):0;const next=state.level<5?['Diatomic elements','Parentheses','Combustion','Systematic balancing'][state.level-1]:'Mastery complete';return `<div class="sp-card"><span class="sp-eyebrow">YOUR PROGRESS</span><h2>Know exactly what to do next</h2><div class="sp-progress"><span style="width:${Math.min(100,state.level/5*100)}%"></span></div><div class="sp-stat-grid"><div class="sp-stat"><b>${state.level}/5</b><span>Level</span></div><div class="sp-stat"><b>${state.solved}</b><span>Equations solved</span></div><div class="sp-stat"><b>${acc}%</b><span>Accuracy</span></div><div class="sp-stat"><b>🔥 ${state.streak}</b><span>Day streak</span></div></div><p><b>Next:</b> ${next}</p></div>`}
function badgesHTML(){const b=[['first','🏅 First Equation'],['counter','⚛ Atom Counter'],['streak','🔥 3-Day Streak'],['expert','🏆 Balancing Expert']];return `<div class="sp-card"><span class="sp-eyebrow">REWARDS</span><h3>Badges</h3><div class="sp-badges">${b.map(x=>`<span class="sp-badge ${state.badges.includes(x[0])?'':'locked'}">${x[1]}</span>`).join('')}</div></div>`}
function daily(){const host=document.querySelector('main .hero');if(!host||document.querySelector('#dailyChallengeCard'))return;const eq=dailyEq();const d=mount(host,`<div id="dailyChallengeCard" class="sp-challenge-box"><span class="sp-eyebrow">🧪 DAILY CHEMISTRY CHALLENGE</span><h2>5 equations · 2 minutes · New challenge every day</h2><p>Keep your streak alive and build balancing speed.</p><div class="sp-actions"><a class="primary" href="personal-quiz.html?daily=1">Start today's challenge →</a></div><small>Today's focus: ${esc(eq.replaceAll('->','→'))}</small></div>`);if(state.dailyDate!==today()){state.dailyDate=today();state.daily=eq;save(state)}}
function levels(){const host=document.querySelector('#paths');if(!host||document.querySelector('#spLevels'))return;const d=mount(host,`<div id="spLevels" class="sp-card"><span class="sp-eyebrow">YOUR CHEMISTRY JOURNEY</span><h2>Unlock the next level</h2><p>Complete practice to move from Beginner to Master.</p><div class="sp-levels">${['Level 1','Level 2','Level 3','Level 4','Master'].map((x,i)=>`<div class="sp-level ${state.level===i+1?'current':''} ${state.level>i+1?'done':''} ${state.level<i+1?'locked':''}"><b>${state.level>i+1?'✓ ':state.level<i+1?'🔒 ':''}${x}</b><small>${['Foundations','Atoms','Structure','Reactions','Mastery'][i]}</small></div>`).join('')}</div><div class="sp-badges">${['🏅 First Equation','⚛ Atom Counter','🔥 Combustion Master','🏆 Balancing Expert'].map(x=>`<span class="sp-badge">${x}</span>`).join('')}</div></div>`);return d}
function coach(){const host=document.querySelector('#paths');if(!host||document.querySelector('#spCoach'))return;const accuracy=state.solved?Math.round(state.correct/state.solved*100):0;const focus=accuracy<70?'core balancing':state.correct<15?'different reaction types':'combustion and harder reactions';mount(host,`<div id="spCoach" class="sp-card sp-coach"><span class="sp-eyebrow">YOUR CHEMISTRY COACH</span><h2>You're building momentum.</h2><p>You've solved <b>${state.solved}</b> equations. ${state.solved?`Your current accuracy is <b>${accuracy}%</b>; keep working on <b>${focus}</b>.`:'Start with one easy equation and I’ll track your progress.'}</p><div class="sp-actions"><a class="primary" href="personal-quiz.html">Practice ${esc(focus)} →</a></div></div>`)}
function exam(){const host=document.querySelector('.quiz-settings');if(!host||document.querySelector('#spExam'))return;const d=document.createElement('div');d.id='spExam';d.className='student-product';d.innerHTML=`<div class="sp-card"><span class="sp-eyebrow">EXAM MODE</span><h2>Exam Practice</h2><p>20 questions · 15 minutes · No hints. Finish with a score and weak-area report.</p><div class="sp-actions"><button id="spStartExam" class="primary" type="button">Start 15-minute exam →</button></div></div>`;host.insertAdjacentElement('afterend',d);d.querySelector('#spStartExam').onclick=()=>{state.exam={started:Date.now(),total:20};save(state);location.href='personal-quiz.html?exam=1'};}
function testTomorrow(){const host=document.querySelector('main .hero');if(!host||document.querySelector('#spTest'))return;mount(host,`<div id="spTest" class="sp-alert"><strong>🚨 Test tomorrow?</strong><span>Use a focused 10-minute review, then practise and finish with a timed mini-test.</span><div class="sp-actions"><a class="primary" href="personal-quiz.html?crash=1">Start the 10-minute review →</a></div></div>`)}
function checker(){const result=document.getElementById('checkResult');if(!result||document.querySelector('#spCheckerCoach'))return;const d=document.createElement('div');d.id='spCheckerCoach';d.className='student-product';d.innerHTML=`<div class="sp-card"><span class="sp-eyebrow">LEARN FROM THE RESULT</span><p>Not quite? The Checker should tell you which element or atom count needs fixing. Use the Balancer for a worked solution.</p></div>`;result.parentElement?.insertAdjacentElement('afterend',d)}
function bindQuiz(){document.querySelectorAll('.stage').forEach(b=>b.addEventListener('click',()=>{}));const quiz=document.querySelector('#quizArea');if(!quiz||quiz.dataset.spBound)return;quiz.dataset.spBound='1';const observer=new MutationObserver(()=>{const buttons=[...quiz.querySelectorAll('button')];buttons.forEach(btn=>{if(btn.dataset.spReward)return;btn.dataset.spReward='1';btn.addEventListener('click',()=>{setTimeout(()=>{const text=quiz.innerText||'';const correct=/correct|✓/i.test(text);reward(correct,'practice');refreshBlocks()},80)})})});observer.observe(quiz,{childList:true,subtree:true});}
function refreshBlocks(){document.querySelectorAll('[data-sp-progress]').forEach(x=>x.innerHTML=progressHTML());}
function profile(){const box=document.getElementById('profileContent');if(!box||document.querySelector('#spProfile'))return;const d=document.createElement('div');d.id='spProfile';d.className='student-product sp-grid';d.innerHTML=progressHTML()+badgesHTML();box.prepend(d)}
function home(){daily();testTomorrow();levels();coach();const host=document.querySelector('#paths')||document.querySelector('main');if(host&&!document.querySelector('#spProgress')){const d=document.createElement('div');d.id='spProgress';d.className='student-product';d.dataset.spProgress='1';d.innerHTML=progressHTML();host.appendChild(d)}}
function init(){addStyles();const p=location.pathname;if(p.endsWith('learn.html')||p.endsWith('/chemistry-equations/'))home();if(p.endsWith('personal-quiz.html')){exam();bindQuiz();if(new URLSearchParams(location.search).has('daily'))daily()}if(p.endsWith('checker.html'))checker();if(p.endsWith('profile.html'))profile()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();