(()=>{
const KEY='chemistryStudentProduct';
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
let state=get(); state.solved=Number(state.solved)||0; state.correct=Number(state.correct)||0; state.xp=Number(state.xp)||0; state.streak=Number(state.streak)||0; state.lastDay=state.lastDay||''; state.level=Number(state.level)||1; state.badges=Array.isArray(state.badges)?state.badges:[]; state.daily=state.daily||''; state.dailyDate=state.dailyDate||''; state.exam=state.exam||null; save(state);
const today=()=>new Date().toISOString().slice(0,10);
const language=()=>{try{const l=localStorage.getItem('chemistryLanguage');return l==='ar'||l==='he'?l:'en'}catch{return'en'}};
const T=(en,ar,he)=>language()==='ar'?ar:language()==='he'?he:en;
const esc=s=>String(s??'').replace(/[&<>\\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;',"'":'&#39;'}[c]));
const addStyles=()=>{if(document.querySelector('#student-product-css,link[data-student-product-css]'))return;const l=document.createElement('link');l.id='student-product-css';l.rel='stylesheet';l.href='student-product.css?v=20260901-rtl-2';document.head.appendChild(l)};
const mount=(el,html)=>{if(!el)return null;const d=document.createElement('div');d.className='student-product';d.innerHTML=html;el.insertAdjacentElement('afterend',d);return d};
const displayChemistry=s=>String(s||'').replace(/Na2/g,'Na₂').replace(/Ca2/g,'Ca₂').replace(/Cl2/g,'Cl₂').replace(/Br2/g,'Br₂').replace(/H2O/g,'H₂O').replace(/H2/g,'H₂').replace(/O2/g,'O₂').replace(/N2/g,'N₂').replace(/F2/g,'F₂').replace(/I2/g,'I₂').replace(/CO2/g,'CO₂').replace(/Fe2/g,'Fe₂').replace(/Al2/g,'Al₂').replace(/P2/g,'P₂').replace(/S2/g,'S₂');
const levels=()=>{const host=document.querySelector('#paths');if(!host||document.querySelector('#spLevels'))return;const levelNames=[T('Level 1','المستوى 1','רמה 1'),T('Level 2','المستوى 2','רמה 2'),T('Level 3','المستوى 3','רמה 3'),T('Level 4','المستوى 4','רמה 4'),T('Master','متقن','מומחה')],topics=[T('Foundations','الأساسيات','יסודות'),T('Atoms','الذرات','אטומים'),T('Structure','البنية','מבנה'),T('Reactions','التفاعلات','תגובות'),T('Mastery','الإتقان','שליטה')];mount(host,`<div id="spLevels" class="sp-card"><span class="sp-eyebrow">${T('YOUR CHEMISTRY JOURNEY','رحلتك في الكيمياء','המסע שלך בכימיה')}</span><h2>${T('Unlock the next level','افتح المستوى التالي','פתחו את הרמה הבאה')}</h2><p>${T('Complete practice to move from Beginner to Master.','أكمل التدريب للانتقال من مبتدئ إلى متقن.','השלימו תרגול כדי להתקדם ממתחילים למומחים.')}</p><div class="sp-levels">${levelNames.map((x,i)=>`<div class="sp-level ${state.level===i+1?'current':''} ${state.level>i+1?'done':''} ${state.level<i+1?'locked':''}"><b>${state.level>i+1?'✓ ':state.level<i+1?'🔒 ':''}${x}</b><small>${topics[i]}</small></div>`).join('')}</div></div>`)}
function badgesHTML(){const b=[['first','🏅 '+T('First Equation','المعادلة الأولى','משוואה ראשונה')],['counter','⚛ '+T('Atom Counter','عداد الذرات','סופר אטומים')],['streak','🔥 '+T('3-Day Streak','سلسلة 3 أيام','רצף של 3 ימים')],['expert','🏆 '+T('Balancing Expert','خبير الموازنة','מומחה לאיזון')]];return `<div class="sp-card"><span class="sp-eyebrow">${T('REWARDS','المكافآت','תגמולים')}</span><h3>${T('Badges','الشارات','תגים')}</h3><div class="sp-badges">${b.map(x=>`<span class="sp-badge ${state.badges.includes(x[0])?'':'locked'}">${x[1]}</span>`).join('')}</div></div>`}
function progressHTML(){const acc=state.solved?Math.round(state.correct/state.solved*100):0;const topics=[T('Diatomic elements','العناصر ثنائية الذرة','יסודות דו־אטומיים'),T('Parentheses','الأقواس','סוגריים'),T('Combustion','الاحتراق','בעירה'),T('Systematic balancing','الموازنة المنهجية','איזון שיטתי')];const next=state.level<5?topics[state.level-1]:T('Mastery complete','اكتمل الإتقان','השליטה הושלמה');return `<div class="sp-card"><span class="sp-eyebrow">${T('YOUR PROGRESS','تقدّمك','ההתקדמות שלך')}</span><h2>${T('Know exactly what to do next','اعرف بالضبط ما الخطوة التالية','דעו בדיוק מה הצעד הבא')}</h2><div class="sp-progress"><span style="width:${Math.min(100,state.level/5*100)}%"></span></div><div class="sp-stat-grid"><div class="sp-stat"><b>${state.level}/5</b><span>${T('Level','المستوى','רמה')}</span></div><div class="sp-stat"><b>${state.solved}</b><span>${T('Equations solved','المعادلات المحلولة','משוואות שנפתרו')}</span></div><div class="sp-stat"><b>${acc}%</b><span>${T('Accuracy','الدقة','דיוק')}</span></div><div class="sp-stat"><b>🔥 ${state.streak}</b><span>${T('Day streak','سلسلة الأيام','רצף ימים')}</span></div></div><p><b>${T('Next:','التالي:','הבא:')}</b> ${next}</p></div>`}
function coach(){const host=document.querySelector('#paths');if(!host||document.querySelector('#spCoach'))return;const accuracy=state.solved?Math.round(state.correct/state.solved*100):0;const focus=accuracy<70?T('core balancing','أساسيات الموازنة','יסודות האיזון'):state.correct<15?T('different reaction types','أنواع التفاعلات المختلفة','סוגי תגובות שונים'):T('combustion and harder reactions','الاحتراق والتفاعلات الأصعب','בעירה ותגובות קשות יותר');const summary=state.solved?T(`Your current accuracy is <b>${accuracy}%</b>; keep working on <b>${focus}</b>.`,`دقتك الحالية <b>${accuracy}%</b>؛ واصل العمل على <b>${focus}</b>.`,`הדיוק הנוכחי שלך הוא <b>${accuracy}%</b>; המשיכו לעבוד על <b>${focus}</b>.`):T('Start with one easy equation and I’ll track your progress.','ابدأ بمعادلة سهلة واحدة وسأتابع تقدّمك.','התחילו במשוואה קלה אחת ואני אעקוב אחר ההתקדמות.');mount(host,`<div id="spCoach" class="sp-card sp-coach"><span class="sp-eyebrow">${T('YOUR CHEMISTRY COACH','مدرّبك في الكيمياء','המאמן שלך בכימיה')}</span><h2>${T("You're building momentum.",'أنت تحقق تقدّمًا.','צוברים תנופה.')}</h2><p>${T(`You've solved <b>${state.solved}</b> equations.`,`لقد حللت <b>${state.solved}</b> معادلات.`,`פתרתם <b>${state.solved}</b> משוואות.`)} ${summary}</p><div class="sp-actions"><a class="primary" href="personal-quiz.html">${T(`Practice ${focus} →`,`تدرّب على ${focus} ←`,`תרגלו ${focus} ←`)}</a></div></div>`)}
function exam(){const host=document.querySelector('.quiz-settings');if(!host||document.querySelector('#spExam'))return;const d=document.createElement('div');d.id='spExam';d.className='student-product';d.innerHTML=`<div class="sp-card"><span class="sp-eyebrow">${T('EXAM MODE','وضع الاختبار','מצב מבחן')}</span><h2>${T('Exam Practice','تدريب الاختبار','תרגול למבחן')}</h2><p>${T('20 questions · 15 minutes · No hints. Finish with a score and weak-area report.','20 سؤالًا · 15 دقيقة · دون تلميحات. أنهِ الاختبار لتحصل على نتيجة وتقرير بنقاط الضعف.','20 שאלות · 15 דקות · ללא רמזים. סיימו עם ציון ודוח על نقاط חולשה.')}</p><div class="sp-actions"><button id="spStartExam" class="primary" type="button">${T('Start 15-minute exam →','ابدأ اختبار 15 دقيقة ←','התחילו מבחן של 15 دقيقة ←')}</button></div></div>`;host.insertAdjacentElement('afterend',d);d.querySelector('#spStartExam').onclick=()=>{state.exam={started:Date.now(),total:20};save(state);location.href='personal-quiz.html?exam=1'};}
function testTomorrow(){const host=document.querySelector('main .hero');if(!host||document.querySelector('#spTest'))return;mount(host,`<div id="spTest" class="sp-alert"><strong>🚨 ${T('Test tomorrow?','عندك اختبار غدًا؟','יש מבחן מחר?')}</strong><span>${T('Use a focused 10-minute review, then practise and finish with a timed mini-test.','استخدم مراجعة مركزة لمدة 10 دقائق، ثم تدرّب وأنهِ باختبار قصير محدد الوقت.','בצעו חזרה ממוקדת של 10 דקות, אחר כך תרגלו וסיימו במבחן קצר ומתוזמן.')}</span><div class="sp-actions"><a class="primary" href="personal-quiz.html?crash=1">${T('Start the 10-minute review →','ابدأ مراجعة العشر دقائق ←','התחילו את החזרה בת 10 הדקות ←')}</a></div></div>`)}
function checker(){const result=document.getElementById('checkResult');if(!result||document.querySelector('#spCheckerCoach'))return;const d=document.createElement('div');d.id='spCheckerCoach';d.className='student-product';d.innerHTML=`<div class="sp-card"><span class="sp-eyebrow">${T('LEARN FROM THE RESULT','تعلّم من النتيجة','למדו מהתוצאה')}</span><p>${T('Not quite? The Checker should tell you which element or atom count needs fixing. Use the Balancer for a worked solution.','ليست صحيحة؟ سيبيّن لك المدقق أي عنصر أو عدد ذرات يحتاج إلى تصحيح. استخدم أداة الموازنة لرؤية حل مفصل.','לא מדויק? הבודק יציין איזה יסוד או מספר אטומים דורש תיקון. השתמשו במאזן כדי לראות פתרון מלא.')}</p></div>`;result.parentElement?.insertAdjacentElement('afterend',d)}
function bindQuiz(){const quiz=document.querySelector('#quizArea');if(!quiz||quiz.dataset.spBound)return;quiz.dataset.spBound='1';const observer=new MutationObserver(()=>{const buttons=[...quiz.querySelectorAll('button')];buttons.forEach(btn=>{if(btn.dataset.spReward)return;btn.dataset.spReward='1';btn.addEventListener('click',()=>{})})});observer.observe(quiz,{childList:true,subtree:true})}
function profile(){const box=document.getElementById('profileContent');if(!box||document.querySelector('#spProfile'))return;const d=document.createElement('div');d.id='spProfile';d.className='student-product sp-grid';d.innerHTML=progressHTML()+badgesHTML();box.prepend(d)}
function home(){testTomorrow();levels();coach();const host=document.querySelector('#paths')||document.querySelector('main');if(host&&!document.querySelector('#spProgress')){const d=document.createElement('div');d.id='spProgress';d.className='student-product';d.dataset.spProgress='1';d.innerHTML=progressHTML();host.appendChild(d)}}
function init(){addStyles();const p=location.pathname;if(p.endsWith('learn.html')||p.endsWith('/chemistry-equations/'))home();if(p.endsWith('personal-quiz.html')){exam();bindQuiz()}if(p.endsWith('checker.html'))checker();if(p.endsWith('profile.html'))profile()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.addEventListener('chemistryLanguageChanged',()=>{document.querySelectorAll('.student-product').forEach(el=>el.remove());init()});
})();
