(()=>{
'use strict';
const KEY='chemistryTheme',LANGUAGE_KEY='chemistryLanguage';
const NAV_LABELS={en:{'learn.html':'Learn','personal-quiz.html':'Quiz','challenges.html':'Challenges','index.html':'Learn','balancer.html':'Balancer','checker.html':'Checker'},ar:{'learn.html':'تعلّم','personal-quiz.html':'اختبار','challenges.html':'التحديات','index.html':'تعلّم','balancer.html':'موازنة المعادلات','checker.html':'التحقق'},he:{'learn.html':'למידה','personal-quiz.html':'חידון','challenges.html':'אתגרים','index.html':'למידה','balancer.html':'איזון משוואות','checker.html':'בדיקה'}};
const THEME_LABELS={en:{dark:'🌙 Dark',light:'☀️ Light'},ar:{dark:'🌙 داكن',light:'☀️ فاتح'},he:{dark:'🌙 כהה',light:'☀️ בהיר'}};
function read(){try{return localStorage.getItem(KEY)==='dark'?'dark':'light'}catch{return'light'}}
function readLanguage(){try{const l=localStorage.getItem(LANGUAGE_KEY);return l==='ar'||l==='he'?l:'en'}catch{return'en'}}
function apply(mode){const dark=mode==='dark';document.documentElement.classList.toggle('dark',dark);document.body.classList.toggle('dark',dark);const b=document.getElementById('themeToggle');if(b){const l=THEME_LABELS[readLanguage()]||THEME_LABELS.en;b.textContent=dark?l.light:l.dark}}
function stabilizeNavigation(){const top=document.querySelector('.topbar'),nav=document.querySelector('.main-nav');if(top)top.style.direction='ltr';if(nav)nav.style.direction='ltr'}
function normalizeNavigation(){
 const nav=document.querySelector('.main-nav');
 if(!nav)return;
 const routes=[['Learn','index.html'],['Quiz','personal-quiz.html'],['Challenges','challenges.html'],['Balancer','balancer.html'],['Checker','checker.html']];
 const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
 const activePage=page==='learn.html'||page==='index.html'||page.includes('lesson')?'index.html':routes.some(([,href])=>href===page)?page:'index.html';
 const links=[...nav.querySelectorAll('a')];
 routes.forEach(([label,href],i)=>{
   let a=links[i];
   if(!a){a=document.createElement('a');nav.appendChild(a)}
   a.href=href;
   a.classList.toggle('active',href===activePage);
 });
 links.slice(routes.length).forEach(a=>a.remove());
 stabilizeNavigation();
}
function restoreLanguageShell(){const lang=readLanguage(),dir=lang==='ar'||lang==='he'?'rtl':'ltr';document.documentElement.lang=lang;document.documentElement.dir=dir;document.body.dir=dir;const labels=NAV_LABELS[lang];document.querySelectorAll('.main-nav a').forEach(a=>{const href=(a.getAttribute('href')||'').split('?')[0].split('#')[0].split('/').pop();if(labels[href])a.textContent=labels[href]});stabilizeNavigation();apply(read())}
function loadGlobalI18n(){if(document.querySelector('script[data-global-i18n]'))return;const loadCore=()=>{const s=document.createElement('script');s.src='i18n-core.js?v=20260901-global-7';s.async=false;s.defer=false;s.dataset.globalI18n='1';s.onload=()=>{const e=document.createElement('script');e.src='i18n-enhancements.js?v=20260901-global-7';e.async=false;e.defer=false;e.onload=()=>window.ChemistryI18n?.refresh?.();document.head.appendChild(e)};document.head.appendChild(s)};if(window.ChemistryTranslations){loadCore();return}const d=document.createElement('script');d.src='i18n-dictionary.js?v=20260901-global-7';d.async=false;d.defer=false;d.dataset.globalI18nDictionary='1';d.onload=loadCore;document.head.appendChild(d)}
function loadModernRefresh(){if(document.querySelector('link[data-modern-refresh],link[data-site-modern-refresh]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='modern-refresh.css?v=20260831-mobile-overflow-2';l.dataset.modernRefresh='1';document.head.appendChild(l)}
function loadStudentProduct(){if(document.querySelector('script[data-student-product]'))return;const l=document.createElement('link');l.id='student-product-css';l.rel='stylesheet';l.href='student-product.css?v=20260901-rtl-2';l.dataset.studentProductCss='1';document.head.appendChild(l);const s=document.createElement('script');s.src='student-product.js?v=20260901-rtl-2';s.defer=true;document.head.appendChild(s)}
function loadAdminToolFix(){if(!location.pathname.endsWith('admin.html')||document.getElementById('admin-tools-font-fix'))return;const s=document.createElement('style');s.id='admin-tools-font-fix';s.textContent='#adminTesting .admin-tools-buttons button{font-size:18px!important;font-weight:700!important;line-height:1.2!important;padding:10px 14px!important}';document.head.appendChild(s)}
function styleLearnDaily(){if(!location.pathname.endsWith('learn.html')||document.getElementById('daily-layout-fix'))return;const s=document.createElement('style');s.id='daily-layout-fix';s.textContent='main>.section{margin-top:22px!important;margin-bottom:22px!important}main .hero{padding-bottom:18px!important;margin-bottom:0!important}main .hero+#daily-stable,main #daily-stable{margin-top:8px!important;margin-bottom:12px!important}main #daily-stable .daily-stable-card{margin:0!important}main #daily-stable+.section{margin-top:10px!important}main #daily-stable .daily-stable-completion-links a.secondary,main #daily-stable .daily-stable-completion-links a.primary{background:linear-gradient(135deg,var(--accent),var(--accent2))!important;color:#fff!important;border:0!important;box-shadow:0 7px 18px rgba(49,88,214,.2)!important}';document.head.appendChild(s)}
function moveDailyAfterHero(){if(!location.pathname.endsWith('learn.html'))return;const daily=document.getElementById('daily-stable'),hero=document.querySelector('main .hero');if(daily&&hero&&hero.nextElementSibling!==daily)hero.insertAdjacentElement('afterend',daily)}
function prepareDailyStart(){if(!location.pathname.endsWith('learn.html')||window.__dailyStartPrepared)return;window.__dailyStartPrepared=true;const daily=document.getElementById('daily-stable');if(!daily)return;const start=daily.querySelector('#dsvStart'),eq=daily.querySelector('#dsvEquation'),note=daily.querySelector('#dsvNote');if(!start||start.hidden)return;const l=readLanguage();if(eq)eq.textContent=l==='ar'?'الاختبار اليومي':l==='he'?'החידון היומי':'Daily quiz';if(note)note.textContent=l==='ar'?'اضغط ابدأ لرؤية معادلة اليوم.':l==='he'?'לחצו על התחלה כדי לראות את המשוואה של היום.':'Click Start to see today’s equation.'}
function completionText(){const l=readLanguage();return l==='ar'?['اكتمل التحدي!','تابع التعلّم','تدرّب أكثر']:l==='he'?['האתגר הושלם!','המשיכו ללמוד','תרגלו עוד']:['Challenge complete!','Keep learning','Practice more']}
function restoreDailyCompletion(){if(!location.pathname.endsWith('learn.html')||window.__dailyCompletionRestored)return;window.__dailyCompletionRestored=true;let checks=0;const timer=setInterval(()=>{checks++;const daily=document.getElementById('daily-stable'),result=document.getElementById('dsvResult');if(!daily||!result){if(checks>120)clearInterval(timer);return}let state={};try{state=JSON.parse(localStorage.getItem('chemistryDailyStable:'+new Date().toISOString().slice(0,10))||'{}')}catch{}if(state.complete&&!result.querySelector('[data-daily-restored]')){result.hidden=false;const [done,learnText,practiceText]=completionText();const eq=daily.querySelector('#dsvEquation'),badge=daily.querySelector('#dsvBadge'),input=daily.querySelector('#dsvInput'),score=daily.querySelector('#dsvScore'),hint=daily.querySelector('#dsvHint');if(eq)eq.textContent=done;if(badge)badge.textContent='✓ '+(readLanguage()==='ar'?'أكملت تحدي اليوم':readLanguage()==='he'?'הושלם היום':'Completed today');if(input)input.disabled=true;if(hint){hint.hidden=true;hint.textContent=''}const wrap=document.createElement('div');wrap.dataset.dailyRestored='1';wrap.style.cssText='display:flex;flex-wrap:wrap;gap:9px;margin-top:12px';const learn=document.createElement('a');learn.className='primary';learn.href='learn.html#course-map';learn.textContent='📚 '+learnText;const practice=document.createElement('a');practice.className='primary';practice.href='personal-quiz.html';practice.textContent='🧪 '+practiceText;wrap.append(learn,practice);result.replaceChildren(result.firstChild||document.createElement('div'));result.appendChild(wrap);if(score&&state.score!=null)score.textContent=String(state.score)}if(result.hidden&&!state.complete){clearInterval(timer);return}if(state.complete)clearInterval(timer);if(checks>120)clearInterval(timer)},250)}
function setupAdminReplay(){if(!location.pathname.endsWith('learn.html'))return;let adminSession=false;try{if(sessionStorage.getItem('chemistryAdminReplay')==='1'){adminSession=true;sessionStorage.setItem('chemistryAdminSession','1');sessionStorage.setItem('chemistryAdminReplayGranted','1');sessionStorage.removeItem('chemistryAdminReplay')}if(sessionStorage.getItem('chemistryAdminSession')==='1')adminSession=true}catch{}if(!adminSession)return;let checks=0;const timer=setInterval(()=>{checks++;const result=document.getElementById('dsvResult');if(!result||result.hidden){if(checks>120)clearInterval(timer);return}if(!result.querySelector('[data-admin-replay]')){const b=document.createElement('button');b.type='button';b.className='secondary';b.dataset.adminReplay='1';b.textContent=readLanguage()==='ar'?'إعادة تحدي اليوم':readLanguage()==='he'?'שחקו שוב באתגר היומי':'Replay Daily Challenge';b.addEventListener('click',()=>{try{sessionStorage.setItem('chemistryAdminReplayGranted','1');sessionStorage.setItem('chemistryAdminSession','1');localStorage.removeItem('chemistryDailyStable:'+new Date().toISOString().slice(0,10))}catch{}location.href='learn.html?adminReplay='+Date.now()});result.appendChild(b)}clearInterval(timer)},250)}
function init(){normalizeNavigation();restoreLanguageShell();loadGlobalI18n();loadModernRefresh();loadStudentProduct();loadAdminToolFix();styleLearnDaily();moveDailyAfterHero();prepareDailyStart();restoreDailyCompletion();setupAdminReplay()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
