package com.reem.nonogrampuzzle;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

public class MainActivity extends Activity {
    static final int PICK_IMAGE=10, CREATE_PDF=11;
    LinearLayout root; Bitmap source; Puzzle current; boolean errorAlert=false; byte[] pendingPdf;
    ArrayList<Puzzle> library=new ArrayList<>(); android.content.SharedPreferences prefs;
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("nonograms",0);loadLibrary();showHome();}
    TextView title(String s){TextView v=new TextView(this);v.setText(s);v.setTextSize(25);v.setTextColor(Color.rgb(25,35,55));v.setTypeface(null,1);v.setPadding(20,22,20,16);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setMinHeight(54);return b;}
    void base(String heading){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(14,10,14,14);root.setBackgroundColor(Color.WHITE);ScrollView sc=new ScrollView(this);sc.addView(root);setContentView(sc);root.addView(title(heading));}
    void showHome(){base("Nonogram Puzzle Maker");TextView t=new TextView(this);t.setText("Turn a picture into a nonogram. Grid sizes are multiples of 5, and generated puzzles are accepted only when the clue system can solve them without guessing.");t.setTextSize(16);t.setPadding(20,0,20,18);root.addView(t);Button make=btn("Create from photo");make.setOnClickListener(v->showCreate());root.addView(make);Button lib=btn("My & public-on-this-device puzzles");lib.setOnClickListener(v->showLibrary());root.addView(lib);Button cur=btn("Curated safe collections");cur.setOnClickListener(v->showCurated());root.addView(cur);TextView note=new TextView(this);note.setText("Sharing note: this first build stores public/private status locally. A real public community backend requires a server/database and moderation service, so no image is uploaded without your own backend credentials.");note.setTextSize(13);note.setPadding(20,18,20,10);root.addView(note);}
    void showCreate(){base("Create puzzle");LinearLayout row=new LinearLayout(this);row.setPadding(10,0,10,10);TextView a=new TextView(this);a.setText("Height (5–50): ");a.setTextSize(16);EditText h=new EditText(this);h.setInputType(2);h.setText("15");TextView b=new TextView(this);b.setText("Width: ");b.setTextSize(16);EditText w=new EditText(this);w.setInputType(2);w.setText("15");row.addView(a);row.addView(h,new LinearLayout.LayoutParams(110,60));row.addView(b);row.addView(w,new LinearLayout.LayoutParams(110,60));root.addView(row);CheckBox color=new CheckBox(this);color.setText("Colored puzzle");color.setChecked(true);root.addView(color);CheckBox pub=new CheckBox(this);pub.setText("Save/share publicly (local public library in this build)");root.addView(pub);TextView selected=new TextView(this);selected.setText("No photo selected");selected.setPadding(20,15,20,15);root.addView(selected);Button pick=btn("Choose photo");pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK_IMAGE);});root.addView(pick);Button gen=btn("Generate nonogram");gen.setOnClickListener(v->{int hh=parseMultiple(h.getText().toString()),ww=parseMultiple(w.getText().toString());if(source==null){toast("Choose a photo first");return;}if(hh<5||ww<5||hh>50||ww>50){toast("Use dimensions from 5 to 50");return;}current=Puzzle.fromBitmap(source,hh,ww,color.isChecked(),pub.isChecked());if(!current.logical){toast("This image cannot produce a no-guess puzzle at this size. Try another size or photo.");return;}current.title="Photo puzzle "+new Date().toString();library.add(current);saveLibrary();showPuzzle(current);});root.addView(gen);Button back=btn("Back");back.setOnClickListener(v->showHome());root.addView(back);}
    int parseMultiple(String s){try{int x=Integer.parseInt(s.trim());return x%5==0?x:(x/5)*5;}catch(Exception e){return 15;}}
    void showLibrary(){base("Puzzle library");if(library.isEmpty()){TextView x=new TextView(this);x.setText("No puzzles yet. Create one or browse the curated examples.");x.setTextSize(16);x.setPadding(20,10,20,20);root.addView(x);}for(Puzzle p:library)addPuzzleCard(p);Button back=btn("Back");back.setOnClickListener(v->showHome());root.addView(back);}
    void addPuzzleCard(Puzzle p){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(10,8,10,8);TextView x=new TextView(this);x.setText(p.title+"\n"+p.h+" × "+p.w+" • "+p.difficulty+" • "+String.format(Locale.US,"%.1f",p.rating)+"★ • "+(p.publicFlag?"Public":"Private"));x.setTextSize(16);card.addView(x);Button open=btn("Open");open.setOnClickListener(v->showPuzzle(p));card.addView(open);root.addView(card);}
    void showCurated(){base("Curated safe collections");TextView intro=new TextView(this);intro.setText("Built-in examples are generated patterns representing nature, geometry and animals. They contain no alcohol or adult content and do not depend on an unmoderated web feed.");intro.setTextSize(15);intro.setPadding(20,0,20,15);root.addView(intro);String[] names={"Leaf","Mountain","Butterfly","Star","Flower"};for(int k=0;k<names.length;k++)addPuzzleCard(Puzzle.pattern(names[k],15,15,k));Button back=btn("Back");back.setOnClickListener(v->showHome());root.addView(back);}
    void showPuzzle(Puzzle p){current=p;base(p.title);TextView meta=new TextView(this);meta.setText(p.h+" × "+p.w+" • difficulty: "+p.difficulty+" • rating "+String.format(Locale.US,"%.1f",p.rating)+"★");meta.setPadding(12,0,12,8);root.addView(meta);PuzzleView pv=new PuzzleView(this,p);root.addView(pv,new LinearLayout.LayoutParams(-1,Math.min(900,dp(560))));LinearLayout tools=new LinearLayout(this);tools.setOrientation(LinearLayout.HORIZONTAL);Button hint=btn("Hint");hint.setOnClickListener(v->pv.hint());tools.addView(hint,new LinearLayout.LayoutParams(0,60,1));Button x=btn("X marks");x.setOnClickListener(v->{pv.xMode=!pv.xMode;x.setText(pv.xMode?"X marks: ON":"X marks");});tools.addView(x,new LinearLayout.LayoutParams(0,60,1));root.addView(tools);CheckBox err=new CheckBox(this);err.setText("Alert on wrong filled cells");err.setChecked(errorAlert);err.setOnCheckedChangeListener((b,c)->errorAlert=c);root.addView(err);CheckBox sol=new CheckBox(this);sol.setText("Show solution");sol.setOnCheckedChangeListener((b,c)->{pv.showSolution=c;pv.invalidate();});root.addView(sol);Button pdf=btn("Export / print PDF");pdf.setOnClickListener(v->makePdf(p));root.addView(pdf);Button rate=btn("Rate this puzzle");rate.setOnClickListener(v->ratePuzzle(p));root.addView(rate);Button back=btn("Back to library");back.setOnClickListener(v->showLibrary());root.addView(back);}
    void ratePuzzle(Puzzle p){final String[] vals={"1","2","3","4","5"};new AlertDialog.Builder(this).setTitle("Your rating").setItems(vals,(d,w)->{int n=Integer.parseInt(vals[w]);p.rating=(p.rating*p.ratingCount+n)/(p.ratingCount+1);p.ratingCount++;saveLibrary();toast("Rating saved");showPuzzle(p);}).show();}
    void makePdf(Puzzle p){try{PdfDocument doc=new PdfDocument();PdfDocument.Page page=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=page.getCanvas();Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setColor(Color.BLACK);paint.setTextSize(22);c.drawText(p.title,30,40,paint);paint.setTextSize(13);c.drawText(p.h+" × "+p.w+" • "+p.difficulty,30,62,paint);float top=100,left=55,size=Math.min(480f/p.w,600f/p.h);for(int r=0;r<p.h;r++)for(int col=0;col<p.w;col++){float x=left+col*size,y=top+r*size;if(p.grid[r][col]){paint.setStyle(Paint.Style.FILL);paint.setColor(p.colorMode?Color.rgb(p.colors[r][col*3],p.colors[r][col*3+1],p.colors[r][col*3+2]):Color.BLACK);c.drawRect(x,y,x+size,y+size,paint);}paint.setStyle(Paint.Style.STROKE);paint.setColor(Color.BLACK);c.drawRect(x,y,x+size,y+size,paint);}doc.finishPage(page);ByteArrayOutputStream out=new ByteArrayOutputStream();doc.writeTo(out);doc.close();pendingPdf=out.toByteArray();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,"nonogram.pdf");startActivityForResult(i,CREATE_PDF);}catch(Exception e){toast("PDF export failed: "+e.getMessage());}}
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+0.5f);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==PICK_IMAGE&&res==RESULT_OK&&data!=null){try{Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}source=MediaStore.Images.Media.getBitmap(getContentResolver(),u);toast("Photo selected");}catch(Exception e){toast("Could not read photo");}}else if(req==CREATE_PDF&&res==RESULT_OK&&data!=null&&pendingPdf!=null){try{OutputStream o=getContentResolver().openOutputStream(data.getData());o.write(pendingPdf);o.close();pendingPdf=null;toast("PDF saved");}catch(Exception e){toast("Could not save PDF");}}}
    void saveLibrary(){StringBuilder sb=new StringBuilder();for(Puzzle p:library)sb.append(p.serialize()).append("\n");prefs.edit().putString("lib",sb.toString()).apply();}
    void loadLibrary(){String s=prefs.getString("lib","");for(String line:s.split("\n"))if(!line.trim().isEmpty())try{library.add(Puzzle.deserialize(line));}catch(Exception ignored){}}
    class PuzzleView extends View {Puzzle p;Paint paint=new Paint(1);boolean xMode=false,showSolution=false;float cell,ox,oy;int selR=-1,selC=-1;PuzzleView(Context c,Puzzle p){super(c);this.p=p;setBackgroundColor(Color.WHITE);}protected void onDraw(Canvas c){super.onDraw(c);float clueW=dp(70),clueH=dp(70);cell=Math.min((getWidth()-clueW-10)/p.w,(getHeight()-clueH-10)/p.h);cell=Math.max(8,cell);ox=clueW;oy=clueH;paint.setTextSize(Math.max(8,cell*.28f));paint.setColor(Color.BLACK);paint.setStyle(Paint.Style.FILL);for(int r=0;r<p.h;r++)for(int col=0;col<p.w;col++){float x=ox+col*cell,y=oy+r*cell;boolean fill=showSolution?p.grid[r][col]:p.player[r][col];if(fill){paint.setColor(p.colorMode?Color.rgb(p.colors[r][col*3],p.colors[r][col*3+1],p.colors[r][col*3+2]):Color.BLACK);c.drawRect(x+1,y+1,x+cell-1,y+cell-1,paint);}else if(!showSolution&&p.mark[r][col]){paint.setColor(Color.DKGRAY);paint.setStrokeWidth(2);c.drawLine(x+cell*.25f,y+cell*.25f,x+cell*.75f,y+cell*.75f,paint);c.drawLine(x+cell*.75f,y+cell*.25f,x+cell*.25f,y+cell*.75f,paint);}paint.setStyle(Paint.Style.STROKE);paint.setColor(Color.LTGRAY);paint.setStrokeWidth(1);c.drawRect(x,y,x+cell,y+cell,paint);paint.setStyle(Paint.Style.FILL);}paint.setTextAlign(Paint.Align.CENTER);for(int r=0;r<p.h;r++)c.drawText(join(p.rowClues[r]),ox/2,oy+r*cell+cell*.65f,paint);for(int col=0;col<p.w;col++)c.drawText(join(p.colClues[col]),ox+col*cell+cell/2,oy/2,paint);paint.setTextAlign(Paint.Align.LEFT);if(selR>=0){paint.setStyle(Paint.Style.STROKE);paint.setColor(Color.BLUE);paint.setStrokeWidth(3);c.drawRect(ox+selC*cell,oy+selR*cell,ox+(selC+1)*cell,oy+(selR+1)*cell,paint);paint.setStyle(Paint.Style.FILL);}}
        String join(int[] a){StringBuilder s=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)s.append(' ');s.append(a[i]);}return s.toString();}
        public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;int c=(int)((e.getX()-ox)/cell),r=(int)((e.getY()-oy)/cell);if(r<0||r>=p.h||c<0||c>=p.w)return true;selR=r;selC=c;if(xMode){p.mark[r][c]=!p.mark[r][c];p.player[r][c]=false;}else{p.mark[r][c]=false;p.player[r][c]=!p.player[r][c];if(errorAlert&&p.player[r][c]&&!p.grid[r][c])toast("That cell is not part of the solution.");}invalidate();if(solved())toast("Solved! Great job.");return true;}
        boolean solved(){for(int r=0;r<p.h;r++)for(int c=0;c<p.w;c++)if(p.player[r][c]!=p.grid[r][c])return false;return true;}void hint(){for(int r=0;r<p.h;r++)for(int c=0;c<p.w;c++)if(p.player[r][c]!=p.grid[r][c]){p.player[r][c]=p.grid[r][c];p.mark[r][c]=false;invalidate();return;}}
    }
    static class Puzzle {String title,difficulty;int h,w;boolean colorMode,publicFlag,logical;boolean[][] grid,player,mark;int[][] rowClues,colClues;int[][] colors;float rating=5f;int ratingCount=1;
        static Puzzle fromBitmap(Bitmap b,int h,int w,boolean color,boolean pub){Puzzle p=new Puzzle();p.h=h;p.w=w;p.colorMode=color;p.publicFlag=pub;p.grid=new boolean[h][w];p.player=new boolean[h][w];p.mark=new boolean[h][w];p.colors=new int[h][w*3];Bitmap x=Bitmap.createScaledBitmap(b,w,h,true);for(int r=0;r<h;r++)for(int c=0;c<w;c++){int z=x.getPixel(c,r),rr=Color.red(z),gg=Color.green(z),bb=Color.blue(z);p.colors[r][c*3]=rr;p.colors[r][c*3+1]=gg;p.colors[r][c*3+2]=bb;float lum=rr*.299f+gg*.587f+bb*.114f;p.grid[r][c]=lum<145;}p.computeClues();p.logical=Solver.isLogicallySolvable(p.grid,p.rowClues,p.colClues);p.difficulty=Solver.difficulty(p);return p;}
        static Puzzle pattern(String name,int h,int w,int kind){Puzzle p=new Puzzle();p.title=name+" curated";p.h=h;p.w=w;p.colorMode=false;p.publicFlag=true;p.grid=new boolean[h][w];p.player=new boolean[h][w];p.mark=new boolean[h][w];p.colors=new int[h][w*3];for(int r=0;r<h;r++)for(int c=0;c<w;c++){boolean on=false;double x=c-(w-1)/2.0,y=r-(h-1)/2.0;if(kind==0)on=(Math.abs(x+y*.45)<2.2&&Math.abs(x-y*.45)<2.2)||(r>9&&Math.abs(c-7)<3);if(kind==1)on=(Math.abs(x)<r*.45&&r>2);if(kind==2){double a=Math.sqrt(x*x+y*y);on=(a<5&&Math.abs(x*y)>5)||(Math.abs(x)<1.5&&y<-4);}if(kind==3)on=(Math.abs(x)<2||Math.abs(y)<2||Math.abs(x+y)<2||Math.abs(x-y)<2);if(kind==4)on=(x*x+y*y<36&&((Math.abs(x)<2)||(Math.abs(y)<2)||Math.abs(x)==Math.abs(y)));p.grid[r][c]=on;}p.computeClues();p.logical=Solver.isLogicallySolvable(p.grid,p.rowClues,p.colClues);p.difficulty=Solver.difficulty(p);return p;}
        void computeClues(){rowClues=new int[h][];colClues=new int[w][];for(int r=0;r<h;r++)rowClues[r]=line(grid[r]);for(int c=0;c<w;c++){boolean[] a=new boolean[h];for(int r=0;r<h;r++)a[r]=grid[r][c];colClues[c]=line(a);}}
        static int[] line(boolean[] a){ArrayList<Integer> z=new ArrayList<>();int n=0;for(boolean b:a){if(b)n++;else if(n>0){z.add(n);n=0;}}if(n>0)z.add(n);if(z.isEmpty())z.add(0);int[] q=new int[z.size()];for(int i=0;i<q.length;i++)q[i]=z.get(i);return q;}
        String serialize(){StringBuilder s=new StringBuilder();s.append(h).append(',').append(w).append(',').append(colorMode?1:0).append(',').append(publicFlag?1:0).append(',').append(rating).append(',').append(ratingCount).append(',').append(title.replace("|"," ")).append('|');for(int r=0;r<h;r++)for(int c=0;c<w;c++)s.append(grid[r][c]?'1':'0');return s.toString();}
        static Puzzle deserialize(String s){String[] a=s.split("\\|",2);String[] m=a[0].split(",",7);Puzzle p=new Puzzle();p.h=Integer.parseInt(m[0]);p.w=Integer.parseInt(m[1]);p.colorMode="1".equals(m[2]);p.publicFlag="1".equals(m[3]);p.rating=Float.parseFloat(m[4]);p.ratingCount=Integer.parseInt(m[5]);p.title=m.length>6?m[6]:"Saved puzzle";p.grid=new boolean[p.h][p.w];p.player=new boolean[p.h][p.w];p.mark=new boolean[p.h][p.w];p.colors=new int[p.h][p.w*3];int k=0;for(int r=0;r<p.h;r++)for(int c=0;c<p.w;c++)p.grid[r][c]=k<a[1].length()&&a[1].charAt(k++)=='1';p.computeClues();p.logical=Solver.isLogicallySolvable(p.grid,p.rowClues,p.colClues);p.difficulty=Solver.difficulty(p);return p;}
    }
    static class Solver {
        static boolean isLogicallySolvable(boolean[][] g,int[][] rows,int[][] cols){int h=g.length,w=g[0].length;byte[][] state=new byte[h][w];boolean progress=true;int loops=0;while(progress&&loops++<500){progress=false;for(int r=0;r<h;r++){ArrayList<boolean[]> pats=patterns(w,rows[r],state[r]);if(pats.isEmpty())return false;progress|=applyRow(state,r,pats);}for(int c=0;c<w;c++){byte[] line=new byte[h];for(int r=0;r<h;r++)line[r]=state[r][c];ArrayList<boolean[]> pats=patterns(h,cols[c],line);if(pats.isEmpty())return false;for(int r=0;r<h;r++){boolean all1=true,all0=true;for(boolean[] q:pats){all1&=q[r];all0&=!q[r];}if(all1&&state[r][c]!=1){state[r][c]=1;progress=true;}else if(all0&&state[r][c]!=2){state[r][c]=2;progress=true;}}}}for(int r=0;r<h;r++)for(int c=0;c<w;c++)if(state[r][c]==0)return false;return true;}
        static boolean applyRow(byte[][] st,int r,ArrayList<boolean[]> pats){boolean pr=false;for(int c=0;c<st[r].length;c++){boolean a=true,b=true;for(boolean[] p:pats){a&=p[c];b&=!p[c];}if(a&&st[r][c]!=1){st[r][c]=1;pr=true;}if(b&&st[r][c]!=2){st[r][c]=2;pr=true;}}return pr;}
        static ArrayList<boolean[]> patterns(int n,int[] clues,byte[] known){ArrayList<boolean[]> out=new ArrayList<>();if(clues.length==1&&clues[0]==0){boolean[] z=new boolean[n];for(int i=0;i<n;i++)if(known[i]==1)return out;out.add(z);return out;}gen(0,0,n,clues,known,new boolean[n],out);return out;}
        static void gen(int pos,int ci,int n,int[] clues,byte[] known,boolean[] a,ArrayList<boolean[]> out){if(ci>=clues.length){for(int i=pos;i<n;i++)if(known[i]==1)return;out.add(a.clone());return;}int len=clues[ci],remain=0;for(int j=ci+1;j<clues.length;j++)remain+=clues[j]+1;for(int start=pos;start+len+remain<=n;start++){boolean ok=true;for(int i=pos;i<start;i++)if(known[i]==1){ok=false;break;}if(!ok)continue;for(int i=start;i<start+len;i++)if(known[i]==2){ok=false;break;}if(!ok)continue;if(start+len<n&&known[start+len]==1)continue;boolean[] old=a.clone();for(int i=start;i<start+len;i++)a[i]=true;gen(start+len+1,ci+1,n,clues,known,a,out);a=old;}}
        static String difficulty(Puzzle p){int cells=p.h*p.w;return cells<=225?"Easy":cells<=625?"Medium":"Hard";}
    }
}
